// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module correlator_correlator_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_VITIS_LOOP_54_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_d1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_d1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_d1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_d1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_d1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_d1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_d1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_d1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_d1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_d1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_d1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_d1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_d1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_d1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_d1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_d1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_d1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_d1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_d1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_address1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_ce1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_we1,
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_we1;
output  [63:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_d1;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_we1;
output  [0:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_d1;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_we1;
output  [63:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_d1;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_we1;
output  [0:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_d1;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_we1;
output  [63:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_d1;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_we1;
output  [0:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_d1;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_we1;
output  [63:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_d1;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_we1;
output  [0:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_d1;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_we1;
output  [63:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_d1;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_we1;
output  [63:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_d1;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_we1;
output  [63:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_d1;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_we1;
output  [63:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_d1;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_we1;
output  [63:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_d1;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_we1;
output  [63:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_d1;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_we1;
output  [63:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_d1;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_we1;
output  [63:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_d1;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_we1;
output  [63:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_d1;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_we1;
output  [63:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_d1;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_we1;
output  [63:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_d1;
output  [10:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_address1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_ce1;
output   correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_we1;
output  [63:0] correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_d1;

reg ap_idle;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_we1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_we1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_we1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_we1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_we1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_we1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_we1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_we1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_we1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_we1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_we1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_we1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_we1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_we1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_we1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_we1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_we1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_we1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_we1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_ce1;
reg correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln52_fu_523_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] select_ln53_1_fu_614_p3;
reg   [3:0] select_ln53_1_reg_742;
wire    ap_block_pp0_stage0_11001;
wire   [10:0] add_ln55_fu_630_p2;
reg   [10:0] add_ln55_reg_746;
wire   [63:0] zext_ln55_fu_681_p1;
wire    ap_block_pp0_stage0;
reg   [10:0] f_fu_112;
wire   [10:0] add_ln54_fu_636_p2;
wire    ap_loop_init;
reg   [3:0] l_fu_116;
reg   [14:0] indvar_flatten_fu_120;
wire   [14:0] select_ln53_2_fu_648_p3;
reg   [1:0] b_fu_124;
wire   [1:0] select_ln52_1_fu_582_p3;
reg   [14:0] indvar_flatten12_fu_128;
wire   [14:0] add_ln52_1_fu_529_p2;
wire   [0:0] icmp_ln53_fu_550_p2;
wire   [0:0] icmp_ln54_fu_570_p2;
wire   [0:0] xor_ln52_fu_564_p2;
wire   [1:0] add_ln52_fu_544_p2;
wire   [3:0] select_ln52_fu_556_p3;
wire   [0:0] and_ln52_fu_576_p2;
wire   [0:0] or_ln53_fu_600_p2;
wire   [3:0] add_ln53_fu_594_p2;
wire   [0:0] trunc_ln53_fu_590_p1;
wire   [10:0] tmp_fu_622_p3;
wire   [10:0] select_ln53_fu_606_p3;
wire   [14:0] add_ln53_1_fu_642_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 f_fu_112 = 11'd0;
#0 l_fu_116 = 4'd0;
#0 indvar_flatten_fu_120 = 15'd0;
#0 b_fu_124 = 2'd0;
#0 indvar_flatten12_fu_128 = 15'd0;
#0 ap_done_reg = 1'b0;
end

correlator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            b_fu_124 <= 2'd0;
        end else if (((icmp_ln52_fu_523_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            b_fu_124 <= select_ln52_1_fu_582_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            f_fu_112 <= 11'd0;
        end else if (((icmp_ln52_fu_523_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            f_fu_112 <= add_ln54_fu_636_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten12_fu_128 <= 15'd0;
        end else if (((icmp_ln52_fu_523_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten12_fu_128 <= add_ln52_1_fu_529_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_120 <= 15'd0;
        end else if (((icmp_ln52_fu_523_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_120 <= select_ln53_2_fu_648_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            l_fu_116 <= 4'd0;
        end else if (((icmp_ln52_fu_523_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            l_fu_116 <= select_ln53_1_fu_614_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln55_reg_746 <= add_ln55_fu_630_p2;
        select_ln53_1_reg_742 <= select_ln53_1_fu_614_p3;
    end
end

always @ (*) begin
    if (((icmp_ln52_fu_523_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln53_1_reg_742 == 4'd7))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln53_1_reg_742 == 4'd6))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln53_1_reg_742 == 4'd5))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln53_1_reg_742 == 4'd4))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln53_1_reg_742 == 4'd3))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln53_1_reg_742 == 4'd2))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln53_1_reg_742 == 4'd1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln53_1_reg_742 == 4'd0))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln53_1_reg_742 == 4'd1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln53_1_reg_742 == 4'd0))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln53_1_reg_742 == 4'd8))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln53_1_reg_742 == 4'd7))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln53_1_reg_742 == 4'd6))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln53_1_reg_742 == 4'd5))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln53_1_reg_742 == 4'd4))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln53_1_reg_742 == 4'd3))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln53_1_reg_742 == 4'd2))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln53_1_reg_742 == 4'd0) & ~(select_ln53_1_reg_742 == 4'd1) & ~(select_ln53_1_reg_742 == 4'd2) & ~(select_ln53_1_reg_742 == 4'd3) & ~(select_ln53_1_reg_742 == 4'd4) & ~(select_ln53_1_reg_742 == 4'd5) & ~(select_ln53_1_reg_742 == 4'd6) & ~(select_ln53_1_reg_742 == 4'd7) & ~(select_ln53_1_reg_742 == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln53_1_reg_742 == 4'd8))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_ce1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln53_1_reg_742 == 4'd0) & ~(select_ln53_1_reg_742 == 4'd1) & ~(select_ln53_1_reg_742 == 4'd2) & ~(select_ln53_1_reg_742 == 4'd3) & ~(select_ln53_1_reg_742 == 4'd4) & ~(select_ln53_1_reg_742 == 4'd5) & ~(select_ln53_1_reg_742 == 4'd6) & ~(select_ln53_1_reg_742 == 4'd7) & ~(select_ln53_1_reg_742 == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_we1 = 1'b1;
    end else begin
        correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_1_fu_529_p2 = (indvar_flatten12_fu_128 + 15'd1);

assign add_ln52_fu_544_p2 = (b_fu_124 + 2'd1);

assign add_ln53_1_fu_642_p2 = (indvar_flatten_fu_120 + 15'd1);

assign add_ln53_fu_594_p2 = (select_ln52_fu_556_p3 + 4'd1);

assign add_ln54_fu_636_p2 = (select_ln53_fu_606_p3 + 11'd1);

assign add_ln55_fu_630_p2 = (tmp_fu_622_p3 + select_ln53_fu_606_p3);

assign and_ln52_fu_576_p2 = (xor_ln52_fu_564_p2 & icmp_ln54_fu_570_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_d1 = 64'd0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_d1 = 64'd0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_d1 = 64'd0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_d1 = 64'd0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_d1 = 1'd0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_d1 = 1'd0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_d1 = 1'd0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_d1 = 1'd0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_d1 = 64'd0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_d1 = 64'd0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_d1 = 64'd0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_d1 = 64'd0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_d1 = 64'd0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_d1 = 64'd0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_d1 = 64'd0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_d1 = 64'd0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_d1 = 64'd0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_d1 = 64'd0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_d1 = 64'd0;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_address1 = zext_ln55_fu_681_p1;

assign correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_d1 = 64'd0;

assign icmp_ln52_fu_523_p2 = ((indvar_flatten12_fu_128 == 15'd20480) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_550_p2 = ((indvar_flatten_fu_120 == 15'd10240) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_570_p2 = ((f_fu_112 == 11'd1024) ? 1'b1 : 1'b0);

assign or_ln53_fu_600_p2 = (icmp_ln53_fu_550_p2 | and_ln52_fu_576_p2);

assign select_ln52_1_fu_582_p3 = ((icmp_ln53_fu_550_p2[0:0] == 1'b1) ? add_ln52_fu_544_p2 : b_fu_124);

assign select_ln52_fu_556_p3 = ((icmp_ln53_fu_550_p2[0:0] == 1'b1) ? 4'd0 : l_fu_116);

assign select_ln53_1_fu_614_p3 = ((and_ln52_fu_576_p2[0:0] == 1'b1) ? add_ln53_fu_594_p2 : select_ln52_fu_556_p3);

assign select_ln53_2_fu_648_p3 = ((icmp_ln53_fu_550_p2[0:0] == 1'b1) ? 15'd1 : add_ln53_1_fu_642_p2);

assign select_ln53_fu_606_p3 = ((or_ln53_fu_600_p2[0:0] == 1'b1) ? 11'd0 : f_fu_112);

assign tmp_fu_622_p3 = {{trunc_ln53_fu_590_p1}, {10'd0}};

assign trunc_ln53_fu_590_p1 = select_ln52_1_fu_582_p3[0:0];

assign xor_ln52_fu_564_p2 = (icmp_ln53_fu_550_p2 ^ 1'd1);

assign zext_ln55_fu_681_p1 = add_ln55_reg_746;

endmodule //correlator_correlator_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_VITIS_LOOP_54_3
