-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pfb_block_decimator_pfb_block_decimator_Pipeline_compute_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_data_TREADY : IN STD_LOGIC;
    bank_selector : IN STD_LOGIC_VECTOR (1 downto 0);
    out_data_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_data_TVALID : OUT STD_LOGIC;
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_ce0 : OUT STD_LOGIC;
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_ce0 : OUT STD_LOGIC;
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_ce0 : OUT STD_LOGIC;
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_ce0 : OUT STD_LOGIC;
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_ce0 : OUT STD_LOGIC;
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_ce0 : OUT STD_LOGIC;
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_ce0 : OUT STD_LOGIC;
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_ce0 : OUT STD_LOGIC;
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_ce0 : OUT STD_LOGIC;
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_ce1 : OUT STD_LOGIC;
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_ce0 : OUT STD_LOGIC;
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_ce1 : OUT STD_LOGIC;
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_ce0 : OUT STD_LOGIC;
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_ce1 : OUT STD_LOGIC;
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_ce0 : OUT STD_LOGIC;
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_ce1 : OUT STD_LOGIC;
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_ce0 : OUT STD_LOGIC;
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_ce1 : OUT STD_LOGIC;
    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_q1 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of pfb_block_decimator_pfb_block_decimator_Pipeline_compute_loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv11_5 : STD_LOGIC_VECTOR (10 downto 0) := "00000000101";
    constant ap_const_lv23_CCD : STD_LOGIC_VECTOR (22 downto 0) := "00000000000110011001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv25_199A : STD_LOGIC_VECTOR (24 downto 0) := "0000000000001100110011010";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv22_CCD : STD_LOGIC_VECTOR (21 downto 0) := "0000000000110011001101";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln34_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal out_data_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal k_1_reg_1144 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln34_fu_527_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln34_reg_1154 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln34_reg_1154_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln34_reg_1154_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_reg_1162 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_1_reg_1162_pp0_iter1_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_10_reg_1167 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_7_reg_1237 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln47_fu_737_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_5_fu_749_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_reg_1283 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_reg_1283_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_fu_772_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_reg_1288 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_reg_1288_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_fu_803_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_reg_1318 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_reg_1318_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_9_fu_826_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_9_reg_1323 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_9_reg_1323_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln47_6_fu_930_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal c_1_fu_942_p13 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_1_reg_1369 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_2_fu_969_p13 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_2_reg_1374 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln48_1_fu_1002_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal mul_ln44_1_fu_1011_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal mul_ln48_2_fu_1023_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal mul_ln44_2_fu_1032_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln34_fu_588_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln34_1_fu_622_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_2_fu_651_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_fu_795_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_1_fu_849_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal phi_urem14_fu_134 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal select_ln34_fu_513_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_phi_urem14_load : STD_LOGIC_VECTOR (10 downto 0);
    signal phi_mul12_fu_138 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    signal add_ln34_2_fu_606_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal k_fu_142 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln34_fu_492_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_k_1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal add_ln34_1_fu_501_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln34_1_fu_507_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln34_fu_521_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln45_fu_535_p0 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln45_fu_535_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln45_fu_535_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln45_fu_551_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln45_2_fu_559_p0 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln45_2_fu_559_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln45_2_fu_559_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_fu_612_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln45_4_cast_fu_599_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln45_1_fu_635_p0 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln45_1_fu_635_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln45_1_fu_635_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_2_fu_664_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_fu_687_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_fu_710_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_fu_710_p13 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_664_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_fu_687_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_749_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_fu_772_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_fu_803_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_9_fu_826_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_857_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_880_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_3_fu_903_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_3_fu_903_p13 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_857_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_880_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_1_fu_942_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_2_fu_969_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln48_1_fu_1002_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln47_2_fu_996_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal mul_ln44_1_fu_1011_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln48_2_fu_1023_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln47_4_fu_1017_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal mul_ln44_2_fu_1032_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1093_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_1075_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_1102_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_1084_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp5_fu_1038_p2 : STD_LOGIC_VECTOR (30 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of tmp5_fu_1038_p2 : signal is "no";
    signal tmp9_fu_1042_p2 : STD_LOGIC_VECTOR (30 downto 0);
    attribute use_dsp48 of tmp9_fu_1042_p2 : signal is "no";
    signal out_sample_M_imag_fu_1056_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_sample_M_real_fu_1046_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1075_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1084_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1093_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1102_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1075_ce : STD_LOGIC;
    signal grp_fu_1084_ce : STD_LOGIC;
    signal grp_fu_1093_ce : STD_LOGIC;
    signal grp_fu_1102_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal mul_ln45_1_fu_635_p00 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln45_2_fu_559_p00 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln45_fu_535_p00 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_condition_283 : BOOLEAN;
    signal tmp_2_fu_664_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_664_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_664_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_664_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_687_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_687_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_687_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_687_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal c_fu_710_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_fu_710_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_fu_710_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_fu_710_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_fu_710_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_5_fu_749_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_749_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_749_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_749_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_6_fu_772_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_6_fu_772_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_6_fu_772_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_6_fu_772_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_803_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_803_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_803_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_803_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_826_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_826_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_826_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_826_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_857_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_857_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_857_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_857_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_880_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_880_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_880_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_880_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal c_3_fu_903_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_3_fu_903_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_3_fu_903_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_3_fu_903_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_3_fu_903_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_1_fu_942_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_1_fu_942_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_1_fu_942_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_1_fu_942_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_1_fu_942_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_2_fu_969_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_2_fu_969_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_2_fu_969_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_2_fu_969_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_2_fu_969_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component pfb_block_decimator_mul_11ns_13ns_23_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (10 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        dout : OUT STD_LOGIC_VECTOR (22 downto 0) );
    end component;


    component pfb_block_decimator_mul_12ns_14ns_25_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (11 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component pfb_block_decimator_sparsemux_9_2_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component pfb_block_decimator_sparsemux_11_3_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        din4 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component pfb_block_decimator_mul_16s_16s_31_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component pfb_block_decimator_mac_muladd_16s_16s_31s_31_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (30 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component pfb_block_decimator_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_11ns_13ns_23_1_1_U18 : component pfb_block_decimator_mul_11ns_13ns_23_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 11,
        din1_WIDTH => 13,
        dout_WIDTH => 23)
    port map (
        din0 => mul_ln45_fu_535_p0,
        din1 => mul_ln45_fu_535_p1,
        dout => mul_ln45_fu_535_p2);

    mul_12ns_14ns_25_1_1_U19 : component pfb_block_decimator_mul_12ns_14ns_25_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 12,
        din1_WIDTH => 14,
        dout_WIDTH => 25)
    port map (
        din0 => mul_ln45_2_fu_559_p0,
        din1 => mul_ln45_2_fu_559_p1,
        dout => mul_ln45_2_fu_559_p2);

    mul_12ns_14ns_25_1_1_U20 : component pfb_block_decimator_mul_12ns_14ns_25_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 12,
        din1_WIDTH => 14,
        dout_WIDTH => 25)
    port map (
        din0 => mul_ln45_1_fu_635_p0,
        din1 => mul_ln45_1_fu_635_p1,
        dout => mul_ln45_1_fu_635_p2);

    sparsemux_9_2_16_1_1_U21 : component pfb_block_decimator_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_q0,
        din1 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_q0,
        din2 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_q0,
        din3 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_q0,
        def => tmp_2_fu_664_p9,
        sel => bank_selector,
        dout => tmp_2_fu_664_p11);

    sparsemux_9_2_16_1_1_U22 : component pfb_block_decimator_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_q0,
        din1 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_q0,
        din2 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_q0,
        din3 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_q0,
        def => tmp_3_fu_687_p9,
        sel => bank_selector,
        dout => tmp_3_fu_687_p11);

    sparsemux_11_3_16_1_1_U23 : component pfb_block_decimator_sparsemux_11_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 16,
        CASE1 => "001",
        din1_WIDTH => 16,
        CASE2 => "010",
        din2_WIDTH => 16,
        CASE3 => "011",
        din3_WIDTH => 16,
        CASE4 => "100",
        din4_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_q1,
        din1 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_q1,
        din2 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_q1,
        din3 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_q1,
        din4 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_q1,
        def => c_fu_710_p11,
        sel => trunc_ln34_reg_1154_pp0_iter1_reg,
        dout => c_fu_710_p13);

    sparsemux_9_2_16_1_1_U24 : component pfb_block_decimator_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "01",
        din0_WIDTH => 16,
        CASE1 => "10",
        din1_WIDTH => 16,
        CASE2 => "11",
        din2_WIDTH => 16,
        CASE3 => "00",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_q0,
        din1 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_q0,
        din2 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_q0,
        din3 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_q0,
        def => tmp_5_fu_749_p9,
        sel => bank_selector,
        dout => tmp_5_fu_749_p11);

    sparsemux_9_2_16_1_1_U25 : component pfb_block_decimator_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "01",
        din0_WIDTH => 16,
        CASE1 => "10",
        din1_WIDTH => 16,
        CASE2 => "11",
        din2_WIDTH => 16,
        CASE3 => "00",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_q0,
        din1 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_q0,
        din2 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_q0,
        din3 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_q0,
        def => tmp_6_fu_772_p9,
        sel => bank_selector,
        dout => tmp_6_fu_772_p11);

    sparsemux_9_2_16_1_1_U26 : component pfb_block_decimator_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 16,
        CASE1 => "11",
        din1_WIDTH => 16,
        CASE2 => "00",
        din2_WIDTH => 16,
        CASE3 => "01",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_q0,
        din1 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_q0,
        din2 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_q0,
        din3 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_q0,
        def => tmp_8_fu_803_p9,
        sel => bank_selector,
        dout => tmp_8_fu_803_p11);

    sparsemux_9_2_16_1_1_U27 : component pfb_block_decimator_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 16,
        CASE1 => "11",
        din1_WIDTH => 16,
        CASE2 => "00",
        din2_WIDTH => 16,
        CASE3 => "01",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_q0,
        din1 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_q0,
        din2 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_q0,
        din3 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_q0,
        def => tmp_9_fu_826_p9,
        sel => bank_selector,
        dout => tmp_9_fu_826_p11);

    sparsemux_9_2_16_1_1_U28 : component pfb_block_decimator_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "11",
        din0_WIDTH => 16,
        CASE1 => "00",
        din1_WIDTH => 16,
        CASE2 => "01",
        din2_WIDTH => 16,
        CASE3 => "10",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_q0,
        din1 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_q0,
        din2 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_q0,
        din3 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_q0,
        def => tmp_s_fu_857_p9,
        sel => bank_selector,
        dout => tmp_s_fu_857_p11);

    sparsemux_9_2_16_1_1_U29 : component pfb_block_decimator_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "11",
        din0_WIDTH => 16,
        CASE1 => "00",
        din1_WIDTH => 16,
        CASE2 => "01",
        din2_WIDTH => 16,
        CASE3 => "10",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_q0,
        din1 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_q0,
        din2 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_q0,
        din3 => pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_q0,
        def => tmp_4_fu_880_p9,
        sel => bank_selector,
        dout => tmp_4_fu_880_p11);

    sparsemux_11_3_16_1_1_U30 : component pfb_block_decimator_sparsemux_11_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "011",
        din0_WIDTH => 16,
        CASE1 => "100",
        din1_WIDTH => 16,
        CASE2 => "000",
        din2_WIDTH => 16,
        CASE3 => "001",
        din3_WIDTH => 16,
        CASE4 => "010",
        din4_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_q1,
        din1 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_q1,
        din2 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_q1,
        din3 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_q1,
        din4 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_q1,
        def => c_3_fu_903_p11,
        sel => trunc_ln34_reg_1154_pp0_iter1_reg,
        dout => c_3_fu_903_p13);

    sparsemux_11_3_16_1_1_U31 : component pfb_block_decimator_sparsemux_11_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "001",
        din0_WIDTH => 16,
        CASE1 => "010",
        din1_WIDTH => 16,
        CASE2 => "011",
        din2_WIDTH => 16,
        CASE3 => "100",
        din3_WIDTH => 16,
        CASE4 => "000",
        din4_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_q0,
        din1 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_q0,
        din2 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_q0,
        din3 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_q0,
        din4 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_q0,
        def => c_1_fu_942_p11,
        sel => trunc_ln34_reg_1154_pp0_iter2_reg,
        dout => c_1_fu_942_p13);

    sparsemux_11_3_16_1_1_U32 : component pfb_block_decimator_sparsemux_11_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "010",
        din0_WIDTH => 16,
        CASE1 => "011",
        din1_WIDTH => 16,
        CASE2 => "100",
        din2_WIDTH => 16,
        CASE3 => "000",
        din3_WIDTH => 16,
        CASE4 => "001",
        din4_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_q0,
        din1 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_q0,
        din2 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_q0,
        din3 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_q0,
        din4 => pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_q0,
        def => c_2_fu_969_p11,
        sel => trunc_ln34_reg_1154_pp0_iter2_reg,
        dout => c_2_fu_969_p13);

    mul_16s_16s_31_1_1_U33 : component pfb_block_decimator_mul_16s_16s_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 31)
    port map (
        din0 => mul_ln48_1_fu_1002_p0,
        din1 => tmp_5_reg_1283_pp0_iter3_reg,
        dout => mul_ln48_1_fu_1002_p2);

    mul_16s_16s_31_1_1_U34 : component pfb_block_decimator_mul_16s_16s_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 31)
    port map (
        din0 => mul_ln44_1_fu_1011_p0,
        din1 => tmp_6_reg_1288_pp0_iter3_reg,
        dout => mul_ln44_1_fu_1011_p2);

    mul_16s_16s_31_1_1_U35 : component pfb_block_decimator_mul_16s_16s_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 31)
    port map (
        din0 => mul_ln48_2_fu_1023_p0,
        din1 => tmp_8_reg_1318_pp0_iter3_reg,
        dout => mul_ln48_2_fu_1023_p2);

    mul_16s_16s_31_1_1_U36 : component pfb_block_decimator_mul_16s_16s_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 31)
    port map (
        din0 => mul_ln44_2_fu_1032_p0,
        din1 => tmp_9_reg_1323_pp0_iter3_reg,
        dout => mul_ln44_2_fu_1032_p2);

    mac_muladd_16s_16s_31s_31_4_1_U37 : component pfb_block_decimator_mac_muladd_16s_16s_31s_31_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 31,
        dout_WIDTH => 31)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1075_p0,
        din1 => tmp_2_fu_664_p11,
        din2 => mul_ln48_1_fu_1002_p2,
        ce => grp_fu_1075_ce,
        dout => grp_fu_1075_p3);

    mac_muladd_16s_16s_31s_31_4_1_U38 : component pfb_block_decimator_mac_muladd_16s_16s_31s_31_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 31,
        dout_WIDTH => 31)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1084_p0,
        din1 => tmp_3_fu_687_p11,
        din2 => mul_ln44_1_fu_1011_p2,
        ce => grp_fu_1084_ce,
        dout => grp_fu_1084_p3);

    mac_muladd_16s_16s_31s_31_4_1_U39 : component pfb_block_decimator_mac_muladd_16s_16s_31s_31_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 31,
        dout_WIDTH => 31)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1093_p0,
        din1 => tmp_s_fu_857_p11,
        din2 => mul_ln48_2_fu_1023_p2,
        ce => grp_fu_1093_ce,
        dout => grp_fu_1093_p3);

    mac_muladd_16s_16s_31s_31_4_1_U40 : component pfb_block_decimator_mac_muladd_16s_16s_31s_31_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 31,
        dout_WIDTH => 31)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1102_p0,
        din1 => tmp_4_fu_880_p11,
        din2 => mul_ln44_2_fu_1032_p2,
        ce => grp_fu_1102_ce,
        dout => grp_fu_1102_p3);

    flow_control_loop_pipe_sequential_init_U : component pfb_block_decimator_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    k_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln34_fu_486_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    k_fu_142 <= add_ln34_fu_492_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_142 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    phi_mul12_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    phi_mul12_fu_138 <= ap_const_lv22_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    phi_mul12_fu_138 <= add_ln34_2_fu_606_p2;
                end if;
            end if; 
        end if;
    end process;

    phi_urem14_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln34_fu_486_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    phi_urem14_fu_134 <= select_ln34_fu_513_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    phi_urem14_fu_134 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                k_1_reg_1144 <= ap_sig_allocacmp_k_1;
                tmp_10_reg_1167 <= mul_ln45_2_fu_559_p2(24 downto 15);
                tmp_1_reg_1162 <= mul_ln45_fu_535_p2(22 downto 14);
                tmp_1_reg_1162_pp0_iter1_reg <= tmp_1_reg_1162;
                tmp_7_reg_1237 <= mul_ln45_1_fu_635_p2(24 downto 15);
                trunc_ln34_reg_1154 <= trunc_ln34_fu_527_p1;
                trunc_ln34_reg_1154_pp0_iter1_reg <= trunc_ln34_reg_1154;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                c_1_reg_1369 <= c_1_fu_942_p13;
                c_2_reg_1374 <= c_2_fu_969_p13;
                tmp_5_reg_1283 <= tmp_5_fu_749_p11;
                tmp_5_reg_1283_pp0_iter3_reg <= tmp_5_reg_1283;
                tmp_6_reg_1288 <= tmp_6_fu_772_p11;
                tmp_6_reg_1288_pp0_iter3_reg <= tmp_6_reg_1288;
                tmp_8_reg_1318 <= tmp_8_fu_803_p11;
                tmp_8_reg_1318_pp0_iter3_reg <= tmp_8_reg_1318;
                tmp_9_reg_1323 <= tmp_9_fu_826_p11;
                tmp_9_reg_1323_pp0_iter3_reg <= tmp_9_reg_1323;
                trunc_ln34_reg_1154_pp0_iter2_reg <= trunc_ln34_reg_1154_pp0_iter1_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln34_1_fu_501_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_urem14_load) + unsigned(ap_const_lv11_1));
    add_ln34_2_fu_606_p2 <= std_logic_vector(unsigned(phi_mul12_fu_138) + unsigned(ap_const_lv22_CCD));
    add_ln34_fu_492_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k_1) + unsigned(ap_const_lv11_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_state6_pp0_stage0_iter5)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter5));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter5, out_data_TREADY, ap_block_state6_pp0_stage0_iter5)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((out_data_TREADY = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter5)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter5, out_data_TREADY, ap_block_state6_pp0_stage0_iter5)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((out_data_TREADY = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter5)));
    end process;


    ap_block_state6_pp0_stage0_iter5_assign_proc : process(out_data_TREADY)
    begin
                ap_block_state6_pp0_stage0_iter5 <= (out_data_TREADY = ap_const_logic_0);
    end process;


    ap_condition_283_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
                ap_condition_283 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln34_fu_486_p2)
    begin
        if (((icmp_ln34_fu_486_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_k_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_fu_142)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_k_1 <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_k_1 <= k_fu_142;
        end if; 
    end process;


    ap_sig_allocacmp_phi_urem14_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, phi_urem14_fu_134, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_phi_urem14_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_phi_urem14_load <= phi_urem14_fu_134;
        end if; 
    end process;

    c_1_fu_942_p11 <= "XXXXXXXXXXXXXXXX";
    c_2_fu_969_p11 <= "XXXXXXXXXXXXXXXX";
    c_3_fu_903_p11 <= "XXXXXXXXXXXXXXXX";
    c_fu_710_p11 <= "XXXXXXXXXXXXXXXX";

    grp_fu_1075_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_1075_ce <= ap_const_logic_1;
        else 
            grp_fu_1075_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_1075_p0 <= sext_ln47_fu_737_p1(16 - 1 downto 0);

    grp_fu_1084_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_1084_ce <= ap_const_logic_1;
        else 
            grp_fu_1084_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_1084_p0 <= sext_ln47_fu_737_p1(16 - 1 downto 0);

    grp_fu_1093_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_1093_ce <= ap_const_logic_1;
        else 
            grp_fu_1093_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_1093_p0 <= sext_ln47_6_fu_930_p1(16 - 1 downto 0);

    grp_fu_1102_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_1102_ce <= ap_const_logic_1;
        else 
            grp_fu_1102_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_1102_p0 <= sext_ln47_6_fu_930_p1(16 - 1 downto 0);
    icmp_ln34_1_fu_507_p2 <= "1" when (unsigned(add_ln34_1_fu_501_p2) < unsigned(ap_const_lv11_5)) else "0";
    icmp_ln34_fu_486_p2 <= "1" when (ap_sig_allocacmp_k_1 = ap_const_lv11_400) else "0";
    mul_ln44_1_fu_1011_p0 <= sext_ln47_2_fu_996_p1(16 - 1 downto 0);
    mul_ln44_2_fu_1032_p0 <= sext_ln47_4_fu_1017_p1(16 - 1 downto 0);
    mul_ln45_1_fu_635_p0 <= mul_ln45_1_fu_635_p00(12 - 1 downto 0);
    mul_ln45_1_fu_635_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln45_4_cast_fu_599_p3),25));
    mul_ln45_1_fu_635_p1 <= ap_const_lv25_199A(14 - 1 downto 0);
    mul_ln45_2_fu_559_p0 <= mul_ln45_2_fu_559_p00(12 - 1 downto 0);
    mul_ln45_2_fu_559_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln45_fu_551_p1),25));
    mul_ln45_2_fu_559_p1 <= ap_const_lv25_199A(14 - 1 downto 0);
    mul_ln45_fu_535_p0 <= mul_ln45_fu_535_p00(11 - 1 downto 0);
    mul_ln45_fu_535_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln34_fu_521_p2),23));
    mul_ln45_fu_535_p1 <= ap_const_lv23_CCD(13 - 1 downto 0);
    mul_ln48_1_fu_1002_p0 <= sext_ln47_2_fu_996_p1(16 - 1 downto 0);
    mul_ln48_2_fu_1023_p0 <= sext_ln47_4_fu_1017_p1(16 - 1 downto 0);
    out_data_TDATA <= (out_sample_M_imag_fu_1056_p4 & out_sample_M_real_fu_1046_p4);

    out_data_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter5, out_data_TREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            out_data_TDATA_blk_n <= out_data_TREADY;
        else 
            out_data_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    out_data_TVALID_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            out_data_TVALID <= ap_const_logic_1;
        else 
            out_data_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    out_sample_M_imag_fu_1056_p4 <= tmp9_fu_1042_p2(30 downto 15);
    out_sample_M_real_fu_1046_p4 <= tmp5_fu_1038_p2(30 downto 15);
    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_address0 <= zext_ln34_fu_588_p1(10 - 1 downto 0);

    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_ce0 <= ap_const_logic_1;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_address0 <= zext_ln34_fu_588_p1(10 - 1 downto 0);

    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_ce0 <= ap_const_logic_1;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_address0 <= zext_ln34_fu_588_p1(10 - 1 downto 0);

    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_ce0 <= ap_const_logic_1;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_address0 <= zext_ln34_fu_588_p1(10 - 1 downto 0);

    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_ce0 <= ap_const_logic_1;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_address0 <= zext_ln34_fu_588_p1(10 - 1 downto 0);

    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_ce0 <= ap_const_logic_1;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_address0 <= zext_ln34_fu_588_p1(10 - 1 downto 0);

    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_ce0 <= ap_const_logic_1;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_address0 <= zext_ln34_fu_588_p1(10 - 1 downto 0);

    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_ce0 <= ap_const_logic_1;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_address0 <= zext_ln34_fu_588_p1(10 - 1 downto 0);

    pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_ce0 <= ap_const_logic_1;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, trunc_ln34_reg_1154_pp0_iter1_reg, zext_ln45_fu_795_p1, zext_ln45_1_fu_849_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if ((trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_3)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address0 <= zext_ln45_1_fu_849_p1(10 - 1 downto 0);
            elsif ((trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_2)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address0 <= zext_ln45_fu_795_p1(10 - 1 downto 0);
            else 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address0 <= "XXXXXXXXXX";
            end if;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address1_assign_proc : process(trunc_ln34_reg_1154, zext_ln34_1_fu_622_p1, zext_ln45_2_fu_651_p1, ap_condition_283)
    begin
        if ((ap_const_boolean_1 = ap_condition_283)) then
            if ((trunc_ln34_reg_1154 = ap_const_lv3_4)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address1 <= zext_ln45_2_fu_651_p1(10 - 1 downto 0);
            elsif ((trunc_ln34_reg_1154 = ap_const_lv3_1)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address1 <= zext_ln34_1_fu_622_p1(10 - 1 downto 0);
            else 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address1 <= "XXXXXXXXXX";
            end if;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_1154_pp0_iter1_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_2)))) then 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_ce0 <= ap_const_logic_1;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln34_reg_1154)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln34_reg_1154 = ap_const_lv3_4)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln34_reg_1154 = ap_const_lv3_1)))) then 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_ce1 <= ap_const_logic_1;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, trunc_ln34_reg_1154_pp0_iter1_reg, zext_ln45_fu_795_p1, zext_ln45_1_fu_849_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if ((trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_1)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address0 <= zext_ln45_1_fu_849_p1(10 - 1 downto 0);
            elsif ((trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_0)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address0 <= zext_ln45_fu_795_p1(10 - 1 downto 0);
            else 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address0 <= "XXXXXXXXXX";
            end if;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address1_assign_proc : process(trunc_ln34_reg_1154, zext_ln34_1_fu_622_p1, zext_ln45_2_fu_651_p1, ap_condition_283)
    begin
        if ((ap_const_boolean_1 = ap_condition_283)) then
            if ((trunc_ln34_reg_1154 = ap_const_lv3_2)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address1 <= zext_ln45_2_fu_651_p1(10 - 1 downto 0);
            elsif ((trunc_ln34_reg_1154 = ap_const_lv3_4)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address1 <= zext_ln34_1_fu_622_p1(10 - 1 downto 0);
            else 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address1 <= "XXXXXXXXXX";
            end if;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_1154_pp0_iter1_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_1)))) then 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_ce0 <= ap_const_logic_1;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln34_reg_1154)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln34_reg_1154 = ap_const_lv3_4)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln34_reg_1154 = ap_const_lv3_2)))) then 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_ce1 <= ap_const_logic_1;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, trunc_ln34_reg_1154_pp0_iter1_reg, zext_ln45_fu_795_p1, zext_ln45_1_fu_849_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if ((trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_0)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address0 <= zext_ln45_1_fu_849_p1(10 - 1 downto 0);
            elsif ((trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_4)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address0 <= zext_ln45_fu_795_p1(10 - 1 downto 0);
            else 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address0 <= "XXXXXXXXXX";
            end if;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address1_assign_proc : process(trunc_ln34_reg_1154, zext_ln34_1_fu_622_p1, zext_ln45_2_fu_651_p1, ap_condition_283)
    begin
        if ((ap_const_boolean_1 = ap_condition_283)) then
            if ((trunc_ln34_reg_1154 = ap_const_lv3_1)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address1 <= zext_ln45_2_fu_651_p1(10 - 1 downto 0);
            elsif ((trunc_ln34_reg_1154 = ap_const_lv3_3)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address1 <= zext_ln34_1_fu_622_p1(10 - 1 downto 0);
            else 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address1 <= "XXXXXXXXXX";
            end if;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_1154_pp0_iter1_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_4)))) then 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_ce0 <= ap_const_logic_1;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln34_reg_1154)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln34_reg_1154 = ap_const_lv3_3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln34_reg_1154 = ap_const_lv3_1)))) then 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_ce1 <= ap_const_logic_1;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, trunc_ln34_reg_1154_pp0_iter1_reg, zext_ln45_fu_795_p1, zext_ln45_1_fu_849_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if ((trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_2)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address0 <= zext_ln45_1_fu_849_p1(10 - 1 downto 0);
            elsif ((trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_1)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address0 <= zext_ln45_fu_795_p1(10 - 1 downto 0);
            else 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address0 <= "XXXXXXXXXX";
            end if;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address1_assign_proc : process(trunc_ln34_reg_1154, zext_ln34_1_fu_622_p1, zext_ln45_2_fu_651_p1, ap_condition_283)
    begin
        if ((ap_const_boolean_1 = ap_condition_283)) then
            if ((trunc_ln34_reg_1154 = ap_const_lv3_3)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address1 <= zext_ln45_2_fu_651_p1(10 - 1 downto 0);
            elsif ((trunc_ln34_reg_1154 = ap_const_lv3_0)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address1 <= zext_ln34_1_fu_622_p1(10 - 1 downto 0);
            else 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address1 <= "XXXXXXXXXX";
            end if;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_1154_pp0_iter1_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_1)))) then 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_ce0 <= ap_const_logic_1;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln34_reg_1154)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln34_reg_1154 = ap_const_lv3_3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln34_reg_1154 = ap_const_lv3_0)))) then 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_ce1 <= ap_const_logic_1;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, trunc_ln34_reg_1154_pp0_iter1_reg, zext_ln45_fu_795_p1, zext_ln45_1_fu_849_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if ((trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_4)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address0 <= zext_ln45_1_fu_849_p1(10 - 1 downto 0);
            elsif ((trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_3)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address0 <= zext_ln45_fu_795_p1(10 - 1 downto 0);
            else 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address0 <= "XXXXXXXXXX";
            end if;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address1_assign_proc : process(trunc_ln34_reg_1154, zext_ln34_1_fu_622_p1, zext_ln45_2_fu_651_p1, ap_condition_283)
    begin
        if ((ap_const_boolean_1 = ap_condition_283)) then
            if ((trunc_ln34_reg_1154 = ap_const_lv3_0)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address1 <= zext_ln45_2_fu_651_p1(10 - 1 downto 0);
            elsif ((trunc_ln34_reg_1154 = ap_const_lv3_2)) then 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address1 <= zext_ln34_1_fu_622_p1(10 - 1 downto 0);
            else 
                pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address1 <= "XXXXXXXXXX";
            end if;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_1154_pp0_iter1_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_4)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_1154_pp0_iter1_reg = ap_const_lv3_3)))) then 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_ce0 <= ap_const_logic_1;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln34_reg_1154)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln34_reg_1154 = ap_const_lv3_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln34_reg_1154 = ap_const_lv3_0)))) then 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_ce1 <= ap_const_logic_1;
        else 
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln34_fu_513_p3 <= 
        add_ln34_1_fu_501_p2 when (icmp_ln34_1_fu_507_p2(0) = '1') else 
        ap_const_lv11_0;
        sext_ln45_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(xor_ln34_fu_521_p2),12));

        sext_ln47_2_fu_996_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(c_1_reg_1369),31));

        sext_ln47_4_fu_1017_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(c_2_reg_1374),31));

        sext_ln47_6_fu_930_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(c_3_fu_903_p13),31));

        sext_ln47_fu_737_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(c_fu_710_p13),31));

    tmp5_fu_1038_p2 <= std_logic_vector(signed(grp_fu_1093_p3) + signed(grp_fu_1075_p3));
    tmp9_fu_1042_p2 <= std_logic_vector(signed(grp_fu_1102_p3) + signed(grp_fu_1084_p3));
    tmp_2_fu_664_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_3_fu_687_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_4_fu_880_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_5_fu_749_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_6_fu_772_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_8_fu_803_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_9_fu_826_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_fu_612_p4 <= phi_mul12_fu_138(21 downto 14);
    tmp_s_fu_857_p9 <= "XXXXXXXXXXXXXXXX";
    trunc_ln34_fu_527_p1 <= ap_sig_allocacmp_phi_urem14_load(3 - 1 downto 0);
    xor_ln34_fu_521_p2 <= (ap_sig_allocacmp_k_1 xor ap_const_lv11_400);
    zext_ln34_1_fu_622_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_612_p4),64));
    zext_ln34_fu_588_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_1_reg_1144),64));
    zext_ln45_1_fu_849_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_reg_1237),64));
    zext_ln45_2_fu_651_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_reg_1167),64));
    zext_ln45_4_cast_fu_599_p3 <= (ap_const_lv1_1 & k_1_reg_1144);
    zext_ln45_fu_795_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_reg_1162_pp0_iter1_reg),64));
end behav;
