-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity correlator_correlator_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_VITIS_LOOP_54_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_d1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_d1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_d1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_d1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_ce1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_we1 : OUT STD_LOGIC;
    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_d1 : OUT STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of correlator_correlator_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_VITIS_LOOP_54_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv15_5000 : STD_LOGIC_VECTOR (14 downto 0) := "101000000000000";
    constant ap_const_lv15_1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv15_2800 : STD_LOGIC_VECTOR (14 downto 0) := "010100000000000";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln52_fu_523_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal select_ln53_1_fu_614_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln53_1_reg_742 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln55_fu_630_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln55_reg_746 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln55_fu_681_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal f_fu_112 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln54_fu_636_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal l_fu_116 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal indvar_flatten_fu_120 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal select_ln53_2_fu_648_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal b_fu_124 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal select_ln52_1_fu_582_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten12_fu_128 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal add_ln52_1_fu_529_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln53_fu_550_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_fu_570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln52_fu_564_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln52_fu_544_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln52_fu_556_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln52_fu_576_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln53_fu_600_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln53_fu_594_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln53_fu_590_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_622_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln53_fu_606_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln53_1_fu_642_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component correlator_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component correlator_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    b_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    b_fu_124 <= ap_const_lv2_0;
                elsif (((icmp_ln52_fu_523_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    b_fu_124 <= select_ln52_1_fu_582_p3;
                end if;
            end if; 
        end if;
    end process;

    f_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    f_fu_112 <= ap_const_lv11_0;
                elsif (((icmp_ln52_fu_523_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    f_fu_112 <= add_ln54_fu_636_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten12_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten12_fu_128 <= ap_const_lv15_0;
                elsif (((icmp_ln52_fu_523_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten12_fu_128 <= add_ln52_1_fu_529_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_120 <= ap_const_lv15_0;
                elsif (((icmp_ln52_fu_523_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_120 <= select_ln53_2_fu_648_p3;
                end if;
            end if; 
        end if;
    end process;

    l_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    l_fu_116 <= ap_const_lv4_0;
                elsif (((icmp_ln52_fu_523_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    l_fu_116 <= select_ln53_1_fu_614_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln55_reg_746 <= add_ln55_fu_630_p2;
                select_ln53_1_reg_742 <= select_ln53_1_fu_614_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln52_1_fu_529_p2 <= std_logic_vector(unsigned(indvar_flatten12_fu_128) + unsigned(ap_const_lv15_1));
    add_ln52_fu_544_p2 <= std_logic_vector(unsigned(b_fu_124) + unsigned(ap_const_lv2_1));
    add_ln53_1_fu_642_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_120) + unsigned(ap_const_lv15_1));
    add_ln53_fu_594_p2 <= std_logic_vector(unsigned(select_ln52_fu_556_p3) + unsigned(ap_const_lv4_1));
    add_ln54_fu_636_p2 <= std_logic_vector(unsigned(select_ln53_fu_606_p3) + unsigned(ap_const_lv11_1));
    add_ln55_fu_630_p2 <= std_logic_vector(unsigned(tmp_fu_622_p3) + unsigned(select_ln53_fu_606_p3));
    and_ln52_fu_576_p2 <= (xor_ln52_fu_564_p2 and icmp_ln54_fu_570_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln52_fu_523_p2)
    begin
        if (((icmp_ln52_fu_523_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_d1 <= ap_const_lv64_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln53_1_reg_742 = ap_const_lv4_7))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_10_we1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_d1 <= ap_const_lv64_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln53_1_reg_742 = ap_const_lv4_6))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_11_we1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_d1 <= ap_const_lv64_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln53_1_reg_742 = ap_const_lv4_5))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_12_we1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_d1 <= ap_const_lv64_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln53_1_reg_742 = ap_const_lv4_4))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_13_we1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_d1 <= ap_const_lv1_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln53_1_reg_742 = ap_const_lv4_3))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_14_we1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_d1 <= ap_const_lv1_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln53_1_reg_742 = ap_const_lv4_2))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_15_we1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_d1 <= ap_const_lv1_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln53_1_reg_742 = ap_const_lv4_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_16_we1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_d1 <= ap_const_lv1_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln53_1_reg_742 = ap_const_lv4_0))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_17_we1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_d1 <= ap_const_lv64_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln53_1_reg_742 = ap_const_lv4_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_18_we1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_d1 <= ap_const_lv64_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln53_1_reg_742 = ap_const_lv4_0))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_19_we1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_d1 <= ap_const_lv64_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln53_1_reg_742 = ap_const_lv4_8))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_d1 <= ap_const_lv64_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln53_1_reg_742 = ap_const_lv4_7))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_2_we1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_d1 <= ap_const_lv64_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln53_1_reg_742 = ap_const_lv4_6))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_3_we1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_d1 <= ap_const_lv64_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln53_1_reg_742 = ap_const_lv4_5))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_4_we1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_d1 <= ap_const_lv64_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln53_1_reg_742 = ap_const_lv4_4))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_5_we1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_d1 <= ap_const_lv64_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln53_1_reg_742 = ap_const_lv4_3))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_6_we1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_d1 <= ap_const_lv64_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln53_1_reg_742 = ap_const_lv4_2))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_7_we1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_d1 <= ap_const_lv64_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if ((not((select_ln53_1_reg_742 = ap_const_lv4_0)) and not((select_ln53_1_reg_742 = ap_const_lv4_1)) and not((select_ln53_1_reg_742 = ap_const_lv4_2)) and not((select_ln53_1_reg_742 = ap_const_lv4_3)) and not((select_ln53_1_reg_742 = ap_const_lv4_4)) and not((select_ln53_1_reg_742 = ap_const_lv4_5)) and not((select_ln53_1_reg_742 = ap_const_lv4_6)) and not((select_ln53_1_reg_742 = ap_const_lv4_7)) and not((select_ln53_1_reg_742 = ap_const_lv4_8)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_8_we1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_d1 <= ap_const_lv64_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln53_1_reg_742 = ap_const_lv4_8))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_9_we1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_address1 <= zext_ln55_fu_681_p1(11 - 1 downto 0);

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_ce1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_d1 <= ap_const_lv64_0;

    correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_we1_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln53_1_reg_742, ap_block_pp0_stage0_11001)
    begin
        if ((not((select_ln53_1_reg_742 = ap_const_lv4_0)) and not((select_ln53_1_reg_742 = ap_const_lv4_1)) and not((select_ln53_1_reg_742 = ap_const_lv4_2)) and not((select_ln53_1_reg_742 = ap_const_lv4_3)) and not((select_ln53_1_reg_742 = ap_const_lv4_4)) and not((select_ln53_1_reg_742 = ap_const_lv4_5)) and not((select_ln53_1_reg_742 = ap_const_lv4_6)) and not((select_ln53_1_reg_742 = ap_const_lv4_7)) and not((select_ln53_1_reg_742 = ap_const_lv4_8)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_we1 <= ap_const_logic_1;
        else 
            correlator_stream_stream_stream_stream_stream_stream_stream_stream_strea_we1 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln52_fu_523_p2 <= "1" when (indvar_flatten12_fu_128 = ap_const_lv15_5000) else "0";
    icmp_ln53_fu_550_p2 <= "1" when (indvar_flatten_fu_120 = ap_const_lv15_2800) else "0";
    icmp_ln54_fu_570_p2 <= "1" when (f_fu_112 = ap_const_lv11_400) else "0";
    or_ln53_fu_600_p2 <= (icmp_ln53_fu_550_p2 or and_ln52_fu_576_p2);
    select_ln52_1_fu_582_p3 <= 
        add_ln52_fu_544_p2 when (icmp_ln53_fu_550_p2(0) = '1') else 
        b_fu_124;
    select_ln52_fu_556_p3 <= 
        ap_const_lv4_0 when (icmp_ln53_fu_550_p2(0) = '1') else 
        l_fu_116;
    select_ln53_1_fu_614_p3 <= 
        add_ln53_fu_594_p2 when (and_ln52_fu_576_p2(0) = '1') else 
        select_ln52_fu_556_p3;
    select_ln53_2_fu_648_p3 <= 
        ap_const_lv15_1 when (icmp_ln53_fu_550_p2(0) = '1') else 
        add_ln53_1_fu_642_p2;
    select_ln53_fu_606_p3 <= 
        ap_const_lv11_0 when (or_ln53_fu_600_p2(0) = '1') else 
        f_fu_112;
    tmp_fu_622_p3 <= (trunc_ln53_fu_590_p1 & ap_const_lv10_0);
    trunc_ln53_fu_590_p1 <= select_ln52_1_fu_582_p3(1 - 1 downto 0);
    xor_ln52_fu_564_p2 <= (icmp_ln53_fu_550_p2 xor ap_const_lv1_1);
    zext_ln55_fu_681_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln55_reg_746),64));
end behav;
