// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pfb_block_decimator_pfb_block_decimator_Pipeline_compute_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_data_TREADY,
        bank_selector,
        out_data_TDATA,
        out_data_TVALID,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_q0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_q0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_q0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_q0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_q0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_q0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_q0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_q0,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_q0,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address1,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_ce1,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_q1,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_q0,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address1,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_ce1,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_q1,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_q0,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address1,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_ce1,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_q1,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_q0,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address1,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_ce1,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_q1,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_q0,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address1,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_ce1,
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   out_data_TREADY;
input  [1:0] bank_selector;
output  [31:0] out_data_TDATA;
output   out_data_TVALID;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_ce0;
input  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_q0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_ce0;
input  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_q0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_ce0;
input  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_q0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_ce0;
input  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_q0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_ce0;
input  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_q0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_ce0;
input  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_q0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_ce0;
input  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_q0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_ce0;
input  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_q0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_ce0;
input  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_q0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address1;
output   pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_ce1;
input  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_q1;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_ce0;
input  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_q0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address1;
output   pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_ce1;
input  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_q1;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_ce0;
input  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_q0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address1;
output   pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_ce1;
input  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_q1;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_ce0;
input  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_q0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address1;
output   pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_ce1;
input  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_q1;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_ce0;
input  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_q0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address1;
output   pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_ce1;
input  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_q1;

reg ap_idle;
reg out_data_TVALID;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_ce0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_ce0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_ce0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_ce0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_ce0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_ce0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_ce0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_ce0;
reg[9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_ce0;
reg[9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address1;
reg pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_ce1;
reg[9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_ce0;
reg[9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address1;
reg pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_ce1;
reg[9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_ce0;
reg[9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address1;
reg pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_ce1;
reg[9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_ce0;
reg[9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address1;
reg pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_ce1;
reg[9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_ce0;
reg[9:0] pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address1;
reg pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_ce1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
reg    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln34_fu_486_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    out_data_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [10:0] k_1_reg_1144;
wire   [2:0] trunc_ln34_fu_527_p1;
reg   [2:0] trunc_ln34_reg_1154;
reg   [2:0] trunc_ln34_reg_1154_pp0_iter1_reg;
reg   [2:0] trunc_ln34_reg_1154_pp0_iter2_reg;
reg   [8:0] tmp_1_reg_1162;
reg   [8:0] tmp_1_reg_1162_pp0_iter1_reg;
reg   [9:0] tmp_10_reg_1167;
reg   [9:0] tmp_7_reg_1237;
wire  signed [30:0] sext_ln47_fu_737_p1;
wire   [15:0] tmp_5_fu_749_p11;
reg   [15:0] tmp_5_reg_1283;
reg  signed [15:0] tmp_5_reg_1283_pp0_iter3_reg;
wire   [15:0] tmp_6_fu_772_p11;
reg   [15:0] tmp_6_reg_1288;
reg  signed [15:0] tmp_6_reg_1288_pp0_iter3_reg;
wire   [15:0] tmp_8_fu_803_p11;
reg   [15:0] tmp_8_reg_1318;
reg  signed [15:0] tmp_8_reg_1318_pp0_iter3_reg;
wire   [15:0] tmp_9_fu_826_p11;
reg   [15:0] tmp_9_reg_1323;
reg  signed [15:0] tmp_9_reg_1323_pp0_iter3_reg;
wire  signed [30:0] sext_ln47_6_fu_930_p1;
wire   [15:0] c_1_fu_942_p13;
reg   [15:0] c_1_reg_1369;
wire   [15:0] c_2_fu_969_p13;
reg   [15:0] c_2_reg_1374;
wire  signed [30:0] mul_ln48_1_fu_1002_p2;
wire  signed [30:0] mul_ln44_1_fu_1011_p2;
wire  signed [30:0] mul_ln48_2_fu_1023_p2;
wire  signed [30:0] mul_ln44_2_fu_1032_p2;
wire   [63:0] zext_ln34_fu_588_p1;
wire   [63:0] zext_ln34_1_fu_622_p1;
wire   [63:0] zext_ln45_2_fu_651_p1;
wire   [63:0] zext_ln45_fu_795_p1;
wire   [63:0] zext_ln45_1_fu_849_p1;
reg   [10:0] phi_urem14_fu_134;
wire   [10:0] select_ln34_fu_513_p3;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_phi_urem14_load;
reg   [21:0] phi_mul12_fu_138;
wire   [21:0] add_ln34_2_fu_606_p2;
reg   [10:0] k_fu_142;
wire   [10:0] add_ln34_fu_492_p2;
reg   [10:0] ap_sig_allocacmp_k_1;
reg    ap_block_pp0_stage0_01001;
wire   [10:0] add_ln34_1_fu_501_p2;
wire   [0:0] icmp_ln34_1_fu_507_p2;
wire  signed [10:0] xor_ln34_fu_521_p2;
wire   [10:0] mul_ln45_fu_535_p0;
wire   [12:0] mul_ln45_fu_535_p1;
wire   [22:0] mul_ln45_fu_535_p2;
wire  signed [11:0] sext_ln45_fu_551_p1;
wire   [11:0] mul_ln45_2_fu_559_p0;
wire   [13:0] mul_ln45_2_fu_559_p1;
wire   [24:0] mul_ln45_2_fu_559_p2;
wire   [7:0] tmp_fu_612_p4;
wire   [11:0] zext_ln45_4_cast_fu_599_p3;
wire   [11:0] mul_ln45_1_fu_635_p0;
wire   [13:0] mul_ln45_1_fu_635_p1;
wire   [24:0] mul_ln45_1_fu_635_p2;
wire   [15:0] tmp_2_fu_664_p9;
wire   [15:0] tmp_3_fu_687_p9;
wire   [15:0] c_fu_710_p11;
wire   [15:0] c_fu_710_p13;
wire  signed [15:0] tmp_2_fu_664_p11;
wire  signed [15:0] tmp_3_fu_687_p11;
wire   [15:0] tmp_5_fu_749_p9;
wire   [15:0] tmp_6_fu_772_p9;
wire   [15:0] tmp_8_fu_803_p9;
wire   [15:0] tmp_9_fu_826_p9;
wire   [15:0] tmp_s_fu_857_p9;
wire   [15:0] tmp_4_fu_880_p9;
wire   [15:0] c_3_fu_903_p11;
wire   [15:0] c_3_fu_903_p13;
wire  signed [15:0] tmp_s_fu_857_p11;
wire  signed [15:0] tmp_4_fu_880_p11;
wire   [15:0] c_1_fu_942_p11;
wire   [15:0] c_2_fu_969_p11;
wire  signed [15:0] mul_ln48_1_fu_1002_p0;
wire  signed [30:0] sext_ln47_2_fu_996_p1;
wire  signed [15:0] mul_ln44_1_fu_1011_p0;
wire  signed [15:0] mul_ln48_2_fu_1023_p0;
wire  signed [30:0] sext_ln47_4_fu_1017_p1;
wire  signed [15:0] mul_ln44_2_fu_1032_p0;
wire  signed [30:0] grp_fu_1093_p3;
wire  signed [30:0] grp_fu_1075_p3;
wire  signed [30:0] grp_fu_1102_p3;
wire  signed [30:0] grp_fu_1084_p3;
(* use_dsp48 = "no" *) wire   [30:0] tmp5_fu_1038_p2;
(* use_dsp48 = "no" *) wire   [30:0] tmp9_fu_1042_p2;
wire   [15:0] out_sample_M_imag_fu_1056_p4;
wire   [15:0] out_sample_M_real_fu_1046_p4;
wire  signed [15:0] grp_fu_1075_p0;
wire  signed [15:0] grp_fu_1084_p0;
wire  signed [15:0] grp_fu_1093_p0;
wire  signed [15:0] grp_fu_1102_p0;
reg    grp_fu_1075_ce;
reg    grp_fu_1084_ce;
reg    grp_fu_1093_ce;
reg    grp_fu_1102_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [24:0] mul_ln45_1_fu_635_p00;
wire   [24:0] mul_ln45_2_fu_559_p00;
wire   [22:0] mul_ln45_fu_535_p00;
reg    ap_condition_283;
wire   [1:0] tmp_2_fu_664_p1;
wire   [1:0] tmp_2_fu_664_p3;
wire  signed [1:0] tmp_2_fu_664_p5;
wire  signed [1:0] tmp_2_fu_664_p7;
wire   [1:0] tmp_3_fu_687_p1;
wire   [1:0] tmp_3_fu_687_p3;
wire  signed [1:0] tmp_3_fu_687_p5;
wire  signed [1:0] tmp_3_fu_687_p7;
wire   [2:0] c_fu_710_p1;
wire   [2:0] c_fu_710_p3;
wire   [2:0] c_fu_710_p5;
wire   [2:0] c_fu_710_p7;
wire  signed [2:0] c_fu_710_p9;
wire   [1:0] tmp_5_fu_749_p1;
wire  signed [1:0] tmp_5_fu_749_p3;
wire  signed [1:0] tmp_5_fu_749_p5;
wire   [1:0] tmp_5_fu_749_p7;
wire   [1:0] tmp_6_fu_772_p1;
wire  signed [1:0] tmp_6_fu_772_p3;
wire  signed [1:0] tmp_6_fu_772_p5;
wire   [1:0] tmp_6_fu_772_p7;
wire  signed [1:0] tmp_8_fu_803_p1;
wire  signed [1:0] tmp_8_fu_803_p3;
wire   [1:0] tmp_8_fu_803_p5;
wire   [1:0] tmp_8_fu_803_p7;
wire  signed [1:0] tmp_9_fu_826_p1;
wire  signed [1:0] tmp_9_fu_826_p3;
wire   [1:0] tmp_9_fu_826_p5;
wire   [1:0] tmp_9_fu_826_p7;
wire  signed [1:0] tmp_s_fu_857_p1;
wire   [1:0] tmp_s_fu_857_p3;
wire   [1:0] tmp_s_fu_857_p5;
wire  signed [1:0] tmp_s_fu_857_p7;
wire  signed [1:0] tmp_4_fu_880_p1;
wire   [1:0] tmp_4_fu_880_p3;
wire   [1:0] tmp_4_fu_880_p5;
wire  signed [1:0] tmp_4_fu_880_p7;
wire   [2:0] c_3_fu_903_p1;
wire  signed [2:0] c_3_fu_903_p3;
wire   [2:0] c_3_fu_903_p5;
wire   [2:0] c_3_fu_903_p7;
wire   [2:0] c_3_fu_903_p9;
wire   [2:0] c_1_fu_942_p1;
wire   [2:0] c_1_fu_942_p3;
wire   [2:0] c_1_fu_942_p5;
wire  signed [2:0] c_1_fu_942_p7;
wire   [2:0] c_1_fu_942_p9;
wire   [2:0] c_2_fu_969_p1;
wire   [2:0] c_2_fu_969_p3;
wire  signed [2:0] c_2_fu_969_p5;
wire   [2:0] c_2_fu_969_p7;
wire   [2:0] c_2_fu_969_p9;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 phi_urem14_fu_134 = 11'd0;
#0 phi_mul12_fu_138 = 22'd0;
#0 k_fu_142 = 11'd0;
#0 ap_done_reg = 1'b0;
end

pfb_block_decimator_mul_11ns_13ns_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 23 ))
mul_11ns_13ns_23_1_1_U18(
    .din0(mul_ln45_fu_535_p0),
    .din1(mul_ln45_fu_535_p1),
    .dout(mul_ln45_fu_535_p2)
);

pfb_block_decimator_mul_12ns_14ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 25 ))
mul_12ns_14ns_25_1_1_U19(
    .din0(mul_ln45_2_fu_559_p0),
    .din1(mul_ln45_2_fu_559_p1),
    .dout(mul_ln45_2_fu_559_p2)
);

pfb_block_decimator_mul_12ns_14ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 25 ))
mul_12ns_14ns_25_1_1_U20(
    .din0(mul_ln45_1_fu_635_p0),
    .din1(mul_ln45_1_fu_635_p1),
    .dout(mul_ln45_1_fu_635_p2)
);

pfb_block_decimator_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U21(
    .din0(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_q0),
    .din1(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_q0),
    .din2(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_q0),
    .din3(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_q0),
    .def(tmp_2_fu_664_p9),
    .sel(bank_selector),
    .dout(tmp_2_fu_664_p11)
);

pfb_block_decimator_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U22(
    .din0(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_q0),
    .din1(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_q0),
    .din2(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_q0),
    .din3(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_q0),
    .def(tmp_3_fu_687_p9),
    .sel(bank_selector),
    .dout(tmp_3_fu_687_p11)
);

pfb_block_decimator_sparsemux_11_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_11_3_16_1_1_U23(
    .din0(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_q1),
    .din1(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_q1),
    .din2(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_q1),
    .din3(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_q1),
    .din4(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_q1),
    .def(c_fu_710_p11),
    .sel(trunc_ln34_reg_1154_pp0_iter1_reg),
    .dout(c_fu_710_p13)
);

pfb_block_decimator_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h3 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h0 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U24(
    .din0(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_q0),
    .din1(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_q0),
    .din2(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_q0),
    .din3(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_q0),
    .def(tmp_5_fu_749_p9),
    .sel(bank_selector),
    .dout(tmp_5_fu_749_p11)
);

pfb_block_decimator_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h3 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h0 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U25(
    .din0(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_q0),
    .din1(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_q0),
    .din2(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_q0),
    .din3(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_q0),
    .def(tmp_6_fu_772_p9),
    .sel(bank_selector),
    .dout(tmp_6_fu_772_p11)
);

pfb_block_decimator_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h3 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h1 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U26(
    .din0(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_q0),
    .din1(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_q0),
    .din2(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_q0),
    .din3(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_q0),
    .def(tmp_8_fu_803_p9),
    .sel(bank_selector),
    .dout(tmp_8_fu_803_p11)
);

pfb_block_decimator_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h3 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h1 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U27(
    .din0(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_q0),
    .din1(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_q0),
    .din2(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_q0),
    .din3(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_q0),
    .def(tmp_9_fu_826_p9),
    .sel(bank_selector),
    .dout(tmp_9_fu_826_p11)
);

pfb_block_decimator_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h3 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h2 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U28(
    .din0(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_q0),
    .din1(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_q0),
    .din2(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_q0),
    .din3(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_q0),
    .def(tmp_s_fu_857_p9),
    .sel(bank_selector),
    .dout(tmp_s_fu_857_p11)
);

pfb_block_decimator_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h3 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h2 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U29(
    .din0(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_q0),
    .din1(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_q0),
    .din2(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_q0),
    .din3(pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_q0),
    .def(tmp_4_fu_880_p9),
    .sel(bank_selector),
    .dout(tmp_4_fu_880_p11)
);

pfb_block_decimator_sparsemux_11_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h3 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h4 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h0 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h1 ),
    .din3_WIDTH( 16 ),
    .CASE4( 3'h2 ),
    .din4_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_11_3_16_1_1_U30(
    .din0(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_q1),
    .din1(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_q1),
    .din2(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_q1),
    .din3(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_q1),
    .din4(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_q1),
    .def(c_3_fu_903_p11),
    .sel(trunc_ln34_reg_1154_pp0_iter1_reg),
    .dout(c_3_fu_903_p13)
);

pfb_block_decimator_sparsemux_11_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h3 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h4 ),
    .din3_WIDTH( 16 ),
    .CASE4( 3'h0 ),
    .din4_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_11_3_16_1_1_U31(
    .din0(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_q0),
    .din1(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_q0),
    .din2(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_q0),
    .din3(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_q0),
    .din4(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_q0),
    .def(c_1_fu_942_p11),
    .sel(trunc_ln34_reg_1154_pp0_iter2_reg),
    .dout(c_1_fu_942_p13)
);

pfb_block_decimator_sparsemux_11_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h2 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h3 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h4 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 16 ),
    .CASE4( 3'h1 ),
    .din4_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_11_3_16_1_1_U32(
    .din0(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_q0),
    .din1(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_q0),
    .din2(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_q0),
    .din3(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_q0),
    .din4(pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_q0),
    .def(c_2_fu_969_p11),
    .sel(trunc_ln34_reg_1154_pp0_iter2_reg),
    .dout(c_2_fu_969_p13)
);

pfb_block_decimator_mul_16s_16s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 31 ))
mul_16s_16s_31_1_1_U33(
    .din0(mul_ln48_1_fu_1002_p0),
    .din1(tmp_5_reg_1283_pp0_iter3_reg),
    .dout(mul_ln48_1_fu_1002_p2)
);

pfb_block_decimator_mul_16s_16s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 31 ))
mul_16s_16s_31_1_1_U34(
    .din0(mul_ln44_1_fu_1011_p0),
    .din1(tmp_6_reg_1288_pp0_iter3_reg),
    .dout(mul_ln44_1_fu_1011_p2)
);

pfb_block_decimator_mul_16s_16s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 31 ))
mul_16s_16s_31_1_1_U35(
    .din0(mul_ln48_2_fu_1023_p0),
    .din1(tmp_8_reg_1318_pp0_iter3_reg),
    .dout(mul_ln48_2_fu_1023_p2)
);

pfb_block_decimator_mul_16s_16s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 31 ))
mul_16s_16s_31_1_1_U36(
    .din0(mul_ln44_2_fu_1032_p0),
    .din1(tmp_9_reg_1323_pp0_iter3_reg),
    .dout(mul_ln44_2_fu_1032_p2)
);

pfb_block_decimator_mac_muladd_16s_16s_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_16s_31s_31_4_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1075_p0),
    .din1(tmp_2_fu_664_p11),
    .din2(mul_ln48_1_fu_1002_p2),
    .ce(grp_fu_1075_ce),
    .dout(grp_fu_1075_p3)
);

pfb_block_decimator_mac_muladd_16s_16s_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_16s_31s_31_4_1_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1084_p0),
    .din1(tmp_3_fu_687_p11),
    .din2(mul_ln44_1_fu_1011_p2),
    .ce(grp_fu_1084_ce),
    .dout(grp_fu_1084_p3)
);

pfb_block_decimator_mac_muladd_16s_16s_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_16s_31s_31_4_1_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1093_p0),
    .din1(tmp_s_fu_857_p11),
    .din2(mul_ln48_2_fu_1023_p2),
    .ce(grp_fu_1093_ce),
    .dout(grp_fu_1093_p3)
);

pfb_block_decimator_mac_muladd_16s_16s_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_16s_31s_31_4_1_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1102_p0),
    .din1(tmp_4_fu_880_p11),
    .din2(mul_ln44_2_fu_1032_p2),
    .ce(grp_fu_1102_ce),
    .dout(grp_fu_1102_p3)
);

pfb_block_decimator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln34_fu_486_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_142 <= add_ln34_fu_492_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_142 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_mul12_fu_138 <= 22'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            phi_mul12_fu_138 <= add_ln34_2_fu_606_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln34_fu_486_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            phi_urem14_fu_134 <= select_ln34_fu_513_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_urem14_fu_134 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        k_1_reg_1144 <= ap_sig_allocacmp_k_1;
        tmp_10_reg_1167 <= {{mul_ln45_2_fu_559_p2[24:15]}};
        tmp_1_reg_1162 <= {{mul_ln45_fu_535_p2[22:14]}};
        tmp_1_reg_1162_pp0_iter1_reg <= tmp_1_reg_1162;
        tmp_7_reg_1237 <= {{mul_ln45_1_fu_635_p2[24:15]}};
        trunc_ln34_reg_1154 <= trunc_ln34_fu_527_p1;
        trunc_ln34_reg_1154_pp0_iter1_reg <= trunc_ln34_reg_1154;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        c_1_reg_1369 <= c_1_fu_942_p13;
        c_2_reg_1374 <= c_2_fu_969_p13;
        tmp_5_reg_1283 <= tmp_5_fu_749_p11;
        tmp_5_reg_1283_pp0_iter3_reg <= tmp_5_reg_1283;
        tmp_6_reg_1288 <= tmp_6_fu_772_p11;
        tmp_6_reg_1288_pp0_iter3_reg <= tmp_6_reg_1288;
        tmp_8_reg_1318 <= tmp_8_fu_803_p11;
        tmp_8_reg_1318_pp0_iter3_reg <= tmp_8_reg_1318;
        tmp_9_reg_1323 <= tmp_9_fu_826_p11;
        tmp_9_reg_1323_pp0_iter3_reg <= tmp_9_reg_1323;
        trunc_ln34_reg_1154_pp0_iter2_reg <= trunc_ln34_reg_1154_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_486_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_k_1 = k_fu_142;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_phi_urem14_load = 11'd0;
    end else begin
        ap_sig_allocacmp_phi_urem14_load = phi_urem14_fu_134;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1075_ce = 1'b1;
    end else begin
        grp_fu_1075_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1084_ce = 1'b1;
    end else begin
        grp_fu_1084_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1093_ce = 1'b1;
    end else begin
        grp_fu_1093_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1102_ce = 1'b1;
    end else begin
        grp_fu_1102_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        out_data_TDATA_blk_n = out_data_TREADY;
    end else begin
        out_data_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        out_data_TVALID = 1'b1;
    end else begin
        out_data_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((trunc_ln34_reg_1154_pp0_iter1_reg == 3'd3)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address0 = zext_ln45_1_fu_849_p1;
        end else if ((trunc_ln34_reg_1154_pp0_iter1_reg == 3'd2)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address0 = zext_ln45_fu_795_p1;
        end else begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address0 = 'bx;
        end
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_283)) begin
        if ((trunc_ln34_reg_1154 == 3'd4)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address1 = zext_ln45_2_fu_651_p1;
        end else if ((trunc_ln34_reg_1154 == 3'd1)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address1 = zext_ln34_1_fu_622_p1;
        end else begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address1 = 'bx;
        end
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln34_reg_1154_pp0_iter1_reg == 3'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln34_reg_1154_pp0_iter1_reg == 3'd2)))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln34_reg_1154 == 3'd4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln34_reg_1154 == 3'd1)))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_ce1 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((trunc_ln34_reg_1154_pp0_iter1_reg == 3'd1)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address0 = zext_ln45_1_fu_849_p1;
        end else if ((trunc_ln34_reg_1154_pp0_iter1_reg == 3'd0)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address0 = zext_ln45_fu_795_p1;
        end else begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address0 = 'bx;
        end
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_283)) begin
        if ((trunc_ln34_reg_1154 == 3'd2)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address1 = zext_ln45_2_fu_651_p1;
        end else if ((trunc_ln34_reg_1154 == 3'd4)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address1 = zext_ln34_1_fu_622_p1;
        end else begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address1 = 'bx;
        end
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln34_reg_1154_pp0_iter1_reg == 3'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln34_reg_1154_pp0_iter1_reg == 3'd1)))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln34_reg_1154 == 3'd4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln34_reg_1154 == 3'd2)))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_ce1 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((trunc_ln34_reg_1154_pp0_iter1_reg == 3'd0)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address0 = zext_ln45_1_fu_849_p1;
        end else if ((trunc_ln34_reg_1154_pp0_iter1_reg == 3'd4)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address0 = zext_ln45_fu_795_p1;
        end else begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address0 = 'bx;
        end
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_283)) begin
        if ((trunc_ln34_reg_1154 == 3'd1)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address1 = zext_ln45_2_fu_651_p1;
        end else if ((trunc_ln34_reg_1154 == 3'd3)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address1 = zext_ln34_1_fu_622_p1;
        end else begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address1 = 'bx;
        end
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln34_reg_1154_pp0_iter1_reg == 3'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln34_reg_1154_pp0_iter1_reg == 3'd4)))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln34_reg_1154 == 3'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln34_reg_1154 == 3'd1)))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_ce1 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((trunc_ln34_reg_1154_pp0_iter1_reg == 3'd2)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address0 = zext_ln45_1_fu_849_p1;
        end else if ((trunc_ln34_reg_1154_pp0_iter1_reg == 3'd1)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address0 = zext_ln45_fu_795_p1;
        end else begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address0 = 'bx;
        end
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_283)) begin
        if ((trunc_ln34_reg_1154 == 3'd3)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address1 = zext_ln45_2_fu_651_p1;
        end else if ((trunc_ln34_reg_1154 == 3'd0)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address1 = zext_ln34_1_fu_622_p1;
        end else begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address1 = 'bx;
        end
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln34_reg_1154_pp0_iter1_reg == 3'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln34_reg_1154_pp0_iter1_reg == 3'd1)))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln34_reg_1154 == 3'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln34_reg_1154 == 3'd0)))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_ce1 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((trunc_ln34_reg_1154_pp0_iter1_reg == 3'd4)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address0 = zext_ln45_1_fu_849_p1;
        end else if ((trunc_ln34_reg_1154_pp0_iter1_reg == 3'd3)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address0 = zext_ln45_fu_795_p1;
        end else begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address0 = 'bx;
        end
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_283)) begin
        if ((trunc_ln34_reg_1154 == 3'd0)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address1 = zext_ln45_2_fu_651_p1;
        end else if ((trunc_ln34_reg_1154 == 3'd2)) begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address1 = zext_ln34_1_fu_622_p1;
        end else begin
            pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address1 = 'bx;
        end
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln34_reg_1154_pp0_iter1_reg == 3'd4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln34_reg_1154_pp0_iter1_reg == 3'd3)))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln34_reg_1154 == 3'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln34_reg_1154 == 3'd0)))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_ce1 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_local_coeffs_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln34_1_fu_501_p2 = (ap_sig_allocacmp_phi_urem14_load + 11'd1);

assign add_ln34_2_fu_606_p2 = (phi_mul12_fu_138 + 22'd3277);

assign add_ln34_fu_492_p2 = (ap_sig_allocacmp_k_1 + 11'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter5 == 1'b1) & ((out_data_TREADY == 1'b0) | (1'b1 == ap_block_state6_pp0_stage0_iter5)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter5 == 1'b1) & ((out_data_TREADY == 1'b0) | (1'b1 == ap_block_state6_pp0_stage0_iter5)));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5 = (out_data_TREADY == 1'b0);
end

always @ (*) begin
    ap_condition_283 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign c_1_fu_942_p11 = 'bx;

assign c_2_fu_969_p11 = 'bx;

assign c_3_fu_903_p11 = 'bx;

assign c_fu_710_p11 = 'bx;

assign grp_fu_1075_p0 = sext_ln47_fu_737_p1;

assign grp_fu_1084_p0 = sext_ln47_fu_737_p1;

assign grp_fu_1093_p0 = sext_ln47_6_fu_930_p1;

assign grp_fu_1102_p0 = sext_ln47_6_fu_930_p1;

assign icmp_ln34_1_fu_507_p2 = ((add_ln34_1_fu_501_p2 < 11'd5) ? 1'b1 : 1'b0);

assign icmp_ln34_fu_486_p2 = ((ap_sig_allocacmp_k_1 == 11'd1024) ? 1'b1 : 1'b0);

assign mul_ln44_1_fu_1011_p0 = sext_ln47_2_fu_996_p1;

assign mul_ln44_2_fu_1032_p0 = sext_ln47_4_fu_1017_p1;

assign mul_ln45_1_fu_635_p0 = mul_ln45_1_fu_635_p00;

assign mul_ln45_1_fu_635_p00 = zext_ln45_4_cast_fu_599_p3;

assign mul_ln45_1_fu_635_p1 = 25'd6554;

assign mul_ln45_2_fu_559_p0 = mul_ln45_2_fu_559_p00;

assign mul_ln45_2_fu_559_p00 = $unsigned(sext_ln45_fu_551_p1);

assign mul_ln45_2_fu_559_p1 = 25'd6554;

assign mul_ln45_fu_535_p0 = mul_ln45_fu_535_p00;

assign mul_ln45_fu_535_p00 = $unsigned(xor_ln34_fu_521_p2);

assign mul_ln45_fu_535_p1 = 23'd3277;

assign mul_ln48_1_fu_1002_p0 = sext_ln47_2_fu_996_p1;

assign mul_ln48_2_fu_1023_p0 = sext_ln47_4_fu_1017_p1;

assign out_data_TDATA = {{out_sample_M_imag_fu_1056_p4}, {out_sample_M_real_fu_1046_p4}};

assign out_sample_M_imag_fu_1056_p4 = {{tmp9_fu_1042_p2[30:15]}};

assign out_sample_M_real_fu_1046_p4 = {{tmp5_fu_1038_p2[30:15]}};

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_address0 = zext_ln34_fu_588_p1;

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_address0 = zext_ln34_fu_588_p1;

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_address0 = zext_ln34_fu_588_p1;

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_address0 = zext_ln34_fu_588_p1;

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_address0 = zext_ln34_fu_588_p1;

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_address0 = zext_ln34_fu_588_p1;

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_address0 = zext_ln34_fu_588_p1;

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_address0 = zext_ln34_fu_588_p1;

assign select_ln34_fu_513_p3 = ((icmp_ln34_1_fu_507_p2[0:0] == 1'b1) ? add_ln34_1_fu_501_p2 : 11'd0);

assign sext_ln45_fu_551_p1 = xor_ln34_fu_521_p2;

assign sext_ln47_2_fu_996_p1 = $signed(c_1_reg_1369);

assign sext_ln47_4_fu_1017_p1 = $signed(c_2_reg_1374);

assign sext_ln47_6_fu_930_p1 = $signed(c_3_fu_903_p13);

assign sext_ln47_fu_737_p1 = $signed(c_fu_710_p13);

assign tmp5_fu_1038_p2 = ($signed(grp_fu_1093_p3) + $signed(grp_fu_1075_p3));

assign tmp9_fu_1042_p2 = ($signed(grp_fu_1102_p3) + $signed(grp_fu_1084_p3));

assign tmp_2_fu_664_p9 = 'bx;

assign tmp_3_fu_687_p9 = 'bx;

assign tmp_4_fu_880_p9 = 'bx;

assign tmp_5_fu_749_p9 = 'bx;

assign tmp_6_fu_772_p9 = 'bx;

assign tmp_8_fu_803_p9 = 'bx;

assign tmp_9_fu_826_p9 = 'bx;

assign tmp_fu_612_p4 = {{phi_mul12_fu_138[21:14]}};

assign tmp_s_fu_857_p9 = 'bx;

assign trunc_ln34_fu_527_p1 = ap_sig_allocacmp_phi_urem14_load[2:0];

assign xor_ln34_fu_521_p2 = (ap_sig_allocacmp_k_1 ^ 11'd1024);

assign zext_ln34_1_fu_622_p1 = tmp_fu_612_p4;

assign zext_ln34_fu_588_p1 = k_1_reg_1144;

assign zext_ln45_1_fu_849_p1 = tmp_7_reg_1237;

assign zext_ln45_2_fu_651_p1 = tmp_10_reg_1167;

assign zext_ln45_4_cast_fu_599_p3 = {{1'd1}, {k_1_reg_1144}};

assign zext_ln45_fu_795_p1 = tmp_1_reg_1162_pp0_iter1_reg;

endmodule //pfb_block_decimator_pfb_block_decimator_Pipeline_compute_loop
