// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pfb_block_decimator_pfb_block_decimator_Pipeline_read_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_data_TVALID,
        in_data_TDATA,
        in_data_TREADY,
        bank_selector,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_we0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_d0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_we0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_d0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_we0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_d0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_we0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_d0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_we0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_d0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_we0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_d0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_we0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_d0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_address0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_ce0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_we0,
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_data_TVALID;
input  [31:0] in_data_TDATA;
output   in_data_TREADY;
input  [1:0] bank_selector;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_ce0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_we0;
output  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_d0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_ce0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_we0;
output  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_d0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_ce0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_we0;
output  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_d0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_ce0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_we0;
output  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_d0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_ce0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_we0;
output  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_d0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_ce0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_we0;
output  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_d0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_ce0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_we0;
output  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_d0;
output  [9:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_address0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_ce0;
output   pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_we0;
output  [15:0] pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_d0;

reg ap_idle;
reg in_data_TREADY;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_ce0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_we0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_ce0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_we0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_ce0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_we0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_ce0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_we0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_ce0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_we0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_ce0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_we0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_ce0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_we0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_ce0;
reg pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln29_fu_204_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_data_TDATA_blk_n;
wire   [63:0] zext_ln29_fu_216_p1;
reg   [10:0] i_fu_76;
wire   [10:0] add_ln29_fu_210_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_i_1;
wire   [1:0] bank_selector_read_read_fu_80_p2;
wire   [15:0] trunc_ln31_fu_228_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_fu_76 = 11'd0;
#0 ap_done_reg = 1'b0;
end

pfb_block_decimator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln29_fu_204_p2 == 1'd0)) begin
            i_fu_76 <= add_ln29_fu_210_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_76 <= 11'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln29_fu_204_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_76;
    end
end

always @ (*) begin
    if (((icmp_ln29_fu_204_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        in_data_TDATA_blk_n = in_data_TVALID;
    end else begin
        in_data_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln29_fu_204_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_data_TREADY = 1'b1;
    end else begin
        in_data_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln29_fu_204_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (bank_selector_read_read_fu_80_p2 == 2'd2))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_we0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln29_fu_204_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (bank_selector_read_read_fu_80_p2 == 2'd1))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_we0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln29_fu_204_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (bank_selector_read_read_fu_80_p2 == 2'd0))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_we0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln29_fu_204_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (bank_selector_read_read_fu_80_p2 == 2'd3))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_we0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln29_fu_204_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (bank_selector_read_read_fu_80_p2 == 2'd2))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_we0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln29_fu_204_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (bank_selector_read_read_fu_80_p2 == 2'd1))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_we0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln29_fu_204_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (bank_selector_read_read_fu_80_p2 == 2'd0))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_we0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_ce0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln29_fu_204_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (bank_selector_read_read_fu_80_p2 == 2'd3))) begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_we0 = 1'b1;
    end else begin
        pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln29_fu_210_p2 = (ap_sig_allocacmp_i_1 + 11'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln29_fu_204_p2 == 1'd0) & (in_data_TVALID == 1'b0)));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bank_selector_read_read_fu_80_p2 = bank_selector;

assign icmp_ln29_fu_204_p2 = ((ap_sig_allocacmp_i_1 == 11'd1024) ? 1'b1 : 1'b0);

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_address0 = zext_ln29_fu_216_p1;

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_1_d0 = {{in_data_TDATA[31:16]}};

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_address0 = zext_ln29_fu_216_p1;

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_2_d0 = {{in_data_TDATA[31:16]}};

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_address0 = zext_ln29_fu_216_p1;

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_3_d0 = {{in_data_TDATA[31:16]}};

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_address0 = zext_ln29_fu_216_p1;

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_4_d0 = trunc_ln31_fu_228_p1;

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_address0 = zext_ln29_fu_216_p1;

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_5_d0 = trunc_ln31_fu_228_p1;

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_address0 = zext_ln29_fu_216_p1;

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_6_d0 = trunc_ln31_fu_228_p1;

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_address0 = zext_ln29_fu_216_p1;

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_7_d0 = trunc_ln31_fu_228_p1;

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_address0 = zext_ln29_fu_216_p1;

assign pfb_block_decimator_stream_stream_ap_fixed_const_branch_memory_d0 = {{in_data_TDATA[31:16]}};

assign trunc_ln31_fu_228_p1 = in_data_TDATA[15:0];

assign zext_ln29_fu_216_p1 = ap_sig_allocacmp_i_1;

endmodule //pfb_block_decimator_pfb_block_decimator_Pipeline_read_loop
