// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pfb_multichannel_decimator_compute_pfb_Pipeline_load_coeffs (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        sext_ln49,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_4_address0,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_4_ce0,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_4_we0,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_4_d0,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_3_address0,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_3_ce0,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_3_we0,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_3_d0,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_2_address0,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_2_ce0,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_2_we0,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_2_d0,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_1_address0,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_1_ce0,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_1_we0,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_1_d0,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_address0,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_ce0,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_we0,
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_d0
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [15:0] m_axi_gmem_WDATA;
output  [1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [15:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [9:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [62:0] sext_ln49;
output  [9:0] compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_4_address0;
output   compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_4_ce0;
output   compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_4_we0;
output  [15:0] compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_4_d0;
output  [9:0] compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_3_address0;
output   compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_3_ce0;
output   compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_3_we0;
output  [15:0] compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_3_d0;
output  [9:0] compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_2_address0;
output   compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_2_ce0;
output   compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_2_we0;
output  [15:0] compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_2_d0;
output  [9:0] compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_1_address0;
output   compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_1_ce0;
output   compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_1_we0;
output  [15:0] compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_1_d0;
output  [9:0] compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_address0;
output   compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_ce0;
output   compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_we0;
output  [15:0] compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem_RREADY;
reg compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_4_ce0;
reg compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_4_we0;
reg compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_3_ce0;
reg compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_3_we0;
reg compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_2_ce0;
reg compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_2_we0;
reg compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_1_ce0;
reg compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_1_we0;
reg compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_ce0;
reg compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_we0;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem_blk_n_R;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
wire   [2:0] trunc_ln49_fu_203_p1;
reg   [2:0] trunc_ln49_reg_305;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [2:0] trunc_ln49_reg_305_pp0_iter1_reg;
reg   [15:0] gmem_addr_read_reg_309;
reg    ap_enable_reg_pp0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln49_fu_191_p2;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter2;
wire   [63:0] zext_ln49_fu_262_p1;
reg   [12:0] phi_urem_fu_78;
wire   [12:0] select_ln49_fu_219_p3;
reg   [25:0] phi_mul_fu_82;
wire   [25:0] add_ln49_1_fu_246_p2;
reg   [12:0] i_fu_86;
wire   [12:0] add_ln49_fu_197_p2;
wire   [12:0] add_ln49_2_fu_207_p2;
wire   [0:0] icmp_ln49_1_fu_213_p2;
wire   [9:0] tmp_fu_252_p4;
wire    ap_CS_fsm_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 phi_urem_fu_78 = 13'd0;
#0 phi_mul_fu_82 = 26'd0;
#0 i_fu_86 = 13'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_86 <= 13'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln49_fu_191_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_fu_86 <= add_ln49_fu_197_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_mul_fu_82 <= 26'd0;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        phi_mul_fu_82 <= add_ln49_1_fu_246_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_urem_fu_78 <= 13'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln49_fu_191_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        phi_urem_fu_78 <= select_ln49_fu_219_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gmem_addr_read_reg_309 <= m_axi_gmem_RDATA;
        trunc_ln49_reg_305 <= trunc_ln49_fu_203_p1;
        trunc_ln49_reg_305_pp0_iter1_reg <= trunc_ln49_reg_305;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((icmp_ln49_fu_191_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_1_ce0 = 1'b1;
    end else begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln49_reg_305_pp0_iter1_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_1_we0 = 1'b1;
    end else begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_2_ce0 = 1'b1;
    end else begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln49_reg_305_pp0_iter1_reg == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_2_we0 = 1'b1;
    end else begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_3_ce0 = 1'b1;
    end else begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln49_reg_305_pp0_iter1_reg == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_3_we0 = 1'b1;
    end else begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_4_ce0 = 1'b1;
    end else begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln49_reg_305_pp0_iter1_reg == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_4_we0 = 1'b1;
    end else begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_ce0 = 1'b1;
    end else begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln49_reg_305_pp0_iter1_reg == 3'd0) & ~(trunc_ln49_reg_305_pp0_iter1_reg == 3'd1) & ~(trunc_ln49_reg_305_pp0_iter1_reg == 3'd2) & ~(trunc_ln49_reg_305_pp0_iter1_reg == 3'd3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_we0 = 1'b1;
    end else begin
        compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        m_axi_gmem_RREADY = 1'b1;
    end else begin
        m_axi_gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln49_fu_191_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) & ~((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((icmp_ln49_fu_191_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln49_1_fu_246_p2 = (phi_mul_fu_82 + 26'd13108);

assign add_ln49_2_fu_207_p2 = (phi_urem_fu_78 + 13'd1);

assign add_ln49_fu_197_p2 = (i_fu_86 + 13'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (m_axi_gmem_RVALID == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_1_address0 = zext_ln49_fu_262_p1;

assign compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_1_d0 = gmem_addr_read_reg_309;

assign compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_2_address0 = zext_ln49_fu_262_p1;

assign compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_2_d0 = gmem_addr_read_reg_309;

assign compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_3_address0 = zext_ln49_fu_262_p1;

assign compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_3_d0 = gmem_addr_read_reg_309;

assign compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_4_address0 = zext_ln49_fu_262_p1;

assign compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_4_d0 = gmem_addr_read_reg_309;

assign compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_address0 = zext_ln49_fu_262_p1;

assign compute_pfb_stream_stream_ap_fixed_16_1_5_3_0_const_local_coeffs_d0 = gmem_addr_read_reg_309;

assign icmp_ln49_1_fu_213_p2 = ((add_ln49_2_fu_207_p2 < 13'd5) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_191_p2 = ((i_fu_86 == 13'd4096) ? 1'b1 : 1'b0);

assign m_axi_gmem_ARADDR = 64'd0;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 32'd0;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_ARVALID = 1'b0;

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_WDATA = 16'd0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 2'd0;

assign m_axi_gmem_WUSER = 1'd0;

assign m_axi_gmem_WVALID = 1'b0;

assign select_ln49_fu_219_p3 = ((icmp_ln49_1_fu_213_p2[0:0] == 1'b1) ? add_ln49_2_fu_207_p2 : 13'd0);

assign tmp_fu_252_p4 = {{phi_mul_fu_82[25:16]}};

assign trunc_ln49_fu_203_p1 = phi_urem_fu_78[2:0];

assign zext_ln49_fu_262_p1 = tmp_fu_252_p4;

endmodule //pfb_multichannel_decimator_compute_pfb_Pipeline_load_coeffs
