// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pfb_multichannel_decimator_read_inputs (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        din_data_i0_TDATA,
        din_data_i0_TVALID,
        din_data_i0_TREADY,
        din_data_q0_TDATA,
        din_data_q0_TVALID,
        din_data_q0_TREADY,
        din_data_i1_TDATA,
        din_data_i1_TVALID,
        din_data_i1_TREADY,
        din_data_q1_TDATA,
        din_data_q1_TVALID,
        din_data_q1_TREADY,
        din_data_i2_TDATA,
        din_data_i2_TVALID,
        din_data_i2_TREADY,
        din_data_q2_TDATA,
        din_data_q2_TVALID,
        din_data_q2_TREADY,
        din_data_i3_TDATA,
        din_data_i3_TVALID,
        din_data_i3_TREADY,
        din_data_q3_TDATA,
        din_data_q3_TVALID,
        din_data_q3_TREADY,
        stream_read_to_compute_din,
        stream_read_to_compute_num_data_valid,
        stream_read_to_compute_fifo_cap,
        stream_read_to_compute_full_n,
        stream_read_to_compute_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] din_data_i0_TDATA;
input   din_data_i0_TVALID;
output   din_data_i0_TREADY;
input  [15:0] din_data_q0_TDATA;
input   din_data_q0_TVALID;
output   din_data_q0_TREADY;
input  [15:0] din_data_i1_TDATA;
input   din_data_i1_TVALID;
output   din_data_i1_TREADY;
input  [15:0] din_data_q1_TDATA;
input   din_data_q1_TVALID;
output   din_data_q1_TREADY;
input  [15:0] din_data_i2_TDATA;
input   din_data_i2_TVALID;
output   din_data_i2_TREADY;
input  [15:0] din_data_q2_TDATA;
input   din_data_q2_TVALID;
output   din_data_q2_TREADY;
input  [15:0] din_data_i3_TDATA;
input   din_data_i3_TVALID;
output   din_data_i3_TREADY;
input  [15:0] din_data_q3_TDATA;
input   din_data_q3_TVALID;
output   din_data_q3_TREADY;
output  [127:0] stream_read_to_compute_din;
input  [4:0] stream_read_to_compute_num_data_valid;
input  [4:0] stream_read_to_compute_fifo_cap;
input   stream_read_to_compute_full_n;
output   stream_read_to_compute_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg stream_read_to_compute_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    din_data_i0_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln12_fu_125_p2;
reg    din_data_q0_TDATA_blk_n;
reg    din_data_i1_TDATA_blk_n;
reg    din_data_q1_TDATA_blk_n;
reg    din_data_i2_TDATA_blk_n;
reg    din_data_q2_TDATA_blk_n;
reg    din_data_i3_TDATA_blk_n;
reg    din_data_q3_TDATA_blk_n;
reg    stream_read_to_compute_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [15:0] pack_i_reg_165;
reg    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [15:0] pack_q_reg_170;
reg   [15:0] pack_i_1_reg_175;
reg   [15:0] pack_q_1_reg_180;
reg   [15:0] pack_i_2_reg_185;
reg   [15:0] pack_q_2_reg_190;
reg   [15:0] pack_i_3_reg_195;
reg   [15:0] pack_q_3_reg_200;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg   [10:0] i_fu_58;
wire   [10:0] i_4_fu_131_p2;
reg    ap_block_pp0_stage0_01001;
wire    ap_CS_fsm_state4;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_din_data_i0_U_apdone_blk;
wire   [15:0] din_data_i0_TDATA_int_regslice;
wire    din_data_i0_TVALID_int_regslice;
reg    din_data_i0_TREADY_int_regslice;
wire    regslice_both_din_data_i0_U_ack_in;
wire    regslice_both_din_data_q0_U_apdone_blk;
wire   [15:0] din_data_q0_TDATA_int_regslice;
wire    din_data_q0_TVALID_int_regslice;
reg    din_data_q0_TREADY_int_regslice;
wire    regslice_both_din_data_q0_U_ack_in;
wire    regslice_both_din_data_i1_U_apdone_blk;
wire   [15:0] din_data_i1_TDATA_int_regslice;
wire    din_data_i1_TVALID_int_regslice;
reg    din_data_i1_TREADY_int_regslice;
wire    regslice_both_din_data_i1_U_ack_in;
wire    regslice_both_din_data_q1_U_apdone_blk;
wire   [15:0] din_data_q1_TDATA_int_regslice;
wire    din_data_q1_TVALID_int_regslice;
reg    din_data_q1_TREADY_int_regslice;
wire    regslice_both_din_data_q1_U_ack_in;
wire    regslice_both_din_data_i2_U_apdone_blk;
wire   [15:0] din_data_i2_TDATA_int_regslice;
wire    din_data_i2_TVALID_int_regslice;
reg    din_data_i2_TREADY_int_regslice;
wire    regslice_both_din_data_i2_U_ack_in;
wire    regslice_both_din_data_q2_U_apdone_blk;
wire   [15:0] din_data_q2_TDATA_int_regslice;
wire    din_data_q2_TVALID_int_regslice;
reg    din_data_q2_TREADY_int_regslice;
wire    regslice_both_din_data_q2_U_ack_in;
wire    regslice_both_din_data_i3_U_apdone_blk;
wire   [15:0] din_data_i3_TDATA_int_regslice;
wire    din_data_i3_TVALID_int_regslice;
reg    din_data_i3_TREADY_int_regslice;
wire    regslice_both_din_data_i3_U_ack_in;
wire    regslice_both_din_data_q3_U_apdone_blk;
wire   [15:0] din_data_q3_TDATA_int_regslice;
wire    din_data_q3_TVALID_int_regslice;
reg    din_data_q3_TREADY_int_regslice;
wire    regslice_both_din_data_q3_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 i_fu_58 = 11'd0;
end

pfb_multichannel_decimator_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_i0_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_i0_TDATA),
    .vld_in(din_data_i0_TVALID),
    .ack_in(regslice_both_din_data_i0_U_ack_in),
    .data_out(din_data_i0_TDATA_int_regslice),
    .vld_out(din_data_i0_TVALID_int_regslice),
    .ack_out(din_data_i0_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_i0_U_apdone_blk)
);

pfb_multichannel_decimator_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_q0_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_q0_TDATA),
    .vld_in(din_data_q0_TVALID),
    .ack_in(regslice_both_din_data_q0_U_ack_in),
    .data_out(din_data_q0_TDATA_int_regslice),
    .vld_out(din_data_q0_TVALID_int_regslice),
    .ack_out(din_data_q0_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_q0_U_apdone_blk)
);

pfb_multichannel_decimator_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_i1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_i1_TDATA),
    .vld_in(din_data_i1_TVALID),
    .ack_in(regslice_both_din_data_i1_U_ack_in),
    .data_out(din_data_i1_TDATA_int_regslice),
    .vld_out(din_data_i1_TVALID_int_regslice),
    .ack_out(din_data_i1_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_i1_U_apdone_blk)
);

pfb_multichannel_decimator_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_q1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_q1_TDATA),
    .vld_in(din_data_q1_TVALID),
    .ack_in(regslice_both_din_data_q1_U_ack_in),
    .data_out(din_data_q1_TDATA_int_regslice),
    .vld_out(din_data_q1_TVALID_int_regslice),
    .ack_out(din_data_q1_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_q1_U_apdone_blk)
);

pfb_multichannel_decimator_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_i2_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_i2_TDATA),
    .vld_in(din_data_i2_TVALID),
    .ack_in(regslice_both_din_data_i2_U_ack_in),
    .data_out(din_data_i2_TDATA_int_regslice),
    .vld_out(din_data_i2_TVALID_int_regslice),
    .ack_out(din_data_i2_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_i2_U_apdone_blk)
);

pfb_multichannel_decimator_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_q2_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_q2_TDATA),
    .vld_in(din_data_q2_TVALID),
    .ack_in(regslice_both_din_data_q2_U_ack_in),
    .data_out(din_data_q2_TDATA_int_regslice),
    .vld_out(din_data_q2_TVALID_int_regslice),
    .ack_out(din_data_q2_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_q2_U_apdone_blk)
);

pfb_multichannel_decimator_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_i3_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_i3_TDATA),
    .vld_in(din_data_i3_TVALID),
    .ack_in(regslice_both_din_data_i3_U_ack_in),
    .data_out(din_data_i3_TDATA_int_regslice),
    .vld_out(din_data_i3_TVALID_int_regslice),
    .ack_out(din_data_i3_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_i3_U_apdone_blk)
);

pfb_multichannel_decimator_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_q3_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_q3_TDATA),
    .vld_in(din_data_q3_TVALID),
    .ack_in(regslice_both_din_data_q3_U_ack_in),
    .data_out(din_data_q3_TDATA_int_regslice),
    .vld_out(din_data_q3_TVALID_int_regslice),
    .ack_out(din_data_q3_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_q3_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_58 <= 11'd0;
    end else if (((icmp_ln12_fu_125_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_fu_58 <= i_4_fu_131_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pack_i_1_reg_175 <= din_data_i1_TDATA_int_regslice;
        pack_i_2_reg_185 <= din_data_i2_TDATA_int_regslice;
        pack_i_3_reg_195 <= din_data_i3_TDATA_int_regslice;
        pack_i_reg_165 <= din_data_i0_TDATA_int_regslice;
        pack_q_1_reg_180 <= din_data_q1_TDATA_int_regslice;
        pack_q_2_reg_190 <= din_data_q2_TDATA_int_regslice;
        pack_q_3_reg_200 <= din_data_q3_TDATA_int_regslice;
        pack_q_reg_170 <= din_data_q0_TDATA_int_regslice;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((icmp_ln12_fu_125_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_125_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_i0_TDATA_blk_n = din_data_i0_TVALID_int_regslice;
    end else begin
        din_data_i0_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_125_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_i0_TREADY_int_regslice = 1'b1;
    end else begin
        din_data_i0_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_125_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_i1_TDATA_blk_n = din_data_i1_TVALID_int_regslice;
    end else begin
        din_data_i1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_125_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_i1_TREADY_int_regslice = 1'b1;
    end else begin
        din_data_i1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_125_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_i2_TDATA_blk_n = din_data_i2_TVALID_int_regslice;
    end else begin
        din_data_i2_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_125_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_i2_TREADY_int_regslice = 1'b1;
    end else begin
        din_data_i2_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_125_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_i3_TDATA_blk_n = din_data_i3_TVALID_int_regslice;
    end else begin
        din_data_i3_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_125_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_i3_TREADY_int_regslice = 1'b1;
    end else begin
        din_data_i3_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_125_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_q0_TDATA_blk_n = din_data_q0_TVALID_int_regslice;
    end else begin
        din_data_q0_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_125_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_q0_TREADY_int_regslice = 1'b1;
    end else begin
        din_data_q0_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_125_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_q1_TDATA_blk_n = din_data_q1_TVALID_int_regslice;
    end else begin
        din_data_q1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_125_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_q1_TREADY_int_regslice = 1'b1;
    end else begin
        din_data_q1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_125_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_q2_TDATA_blk_n = din_data_q2_TVALID_int_regslice;
    end else begin
        din_data_q2_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_125_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_q2_TREADY_int_regslice = 1'b1;
    end else begin
        din_data_q2_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_125_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_q3_TDATA_blk_n = din_data_q3_TVALID_int_regslice;
    end else begin
        din_data_q3_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_125_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_q3_TREADY_int_regslice = 1'b1;
    end else begin
        din_data_q3_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_read_to_compute_blk_n = stream_read_to_compute_full_n;
    end else begin
        stream_read_to_compute_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_read_to_compute_write = 1'b1;
    end else begin
        stream_read_to_compute_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln12_fu_125_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln12_fu_125_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (((icmp_ln12_fu_125_p2 == 1'd0) & (din_data_q3_TVALID_int_regslice == 1'b0)) | ((icmp_ln12_fu_125_p2 == 1'd0) & (din_data_i3_TVALID_int_regslice == 1'b0)) | ((icmp_ln12_fu_125_p2 == 1'd0) & (din_data_q2_TVALID_int_regslice == 1'b0)) | ((icmp_ln12_fu_125_p2 == 1'd0) & (din_data_i2_TVALID_int_regslice == 1'b0)) | ((icmp_ln12_fu_125_p2 == 1'd0) & (din_data_q1_TVALID_int_regslice == 1'b0)) | ((icmp_ln12_fu_125_p2 == 1'd0) & (din_data_i1_TVALID_int_regslice == 1'b0)) | ((icmp_ln12_fu_125_p2 == 1'd0) & (din_data_q0_TVALID_int_regslice == 1'b0)) | ((icmp_ln12_fu_125_p2 == 1'd0) & (din_data_i0_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (stream_read_to_compute_full_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign din_data_i0_TREADY = regslice_both_din_data_i0_U_ack_in;

assign din_data_i1_TREADY = regslice_both_din_data_i1_U_ack_in;

assign din_data_i2_TREADY = regslice_both_din_data_i2_U_ack_in;

assign din_data_i3_TREADY = regslice_both_din_data_i3_U_ack_in;

assign din_data_q0_TREADY = regslice_both_din_data_q0_U_ack_in;

assign din_data_q1_TREADY = regslice_both_din_data_q1_U_ack_in;

assign din_data_q2_TREADY = regslice_both_din_data_q2_U_ack_in;

assign din_data_q3_TREADY = regslice_both_din_data_q3_U_ack_in;

assign i_4_fu_131_p2 = (i_fu_58 + 11'd1);

assign icmp_ln12_fu_125_p2 = ((i_fu_58 == 11'd1024) ? 1'b1 : 1'b0);

assign stream_read_to_compute_din = {{{{{{{{pack_q_3_reg_200}, {pack_i_3_reg_195}}, {pack_q_2_reg_190}}, {pack_i_2_reg_185}}, {pack_q_1_reg_180}}, {pack_i_1_reg_175}}, {pack_q_reg_170}}, {pack_i_reg_165}};

endmodule //pfb_multichannel_decimator_read_inputs
