-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pfb_multichannel_decimator_read_inputs is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    din_data_i0_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_i0_TVALID : IN STD_LOGIC;
    din_data_i0_TREADY : OUT STD_LOGIC;
    din_data_q0_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_q0_TVALID : IN STD_LOGIC;
    din_data_q0_TREADY : OUT STD_LOGIC;
    din_data_i1_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_i1_TVALID : IN STD_LOGIC;
    din_data_i1_TREADY : OUT STD_LOGIC;
    din_data_q1_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_q1_TVALID : IN STD_LOGIC;
    din_data_q1_TREADY : OUT STD_LOGIC;
    din_data_i2_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_i2_TVALID : IN STD_LOGIC;
    din_data_i2_TREADY : OUT STD_LOGIC;
    din_data_q2_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_q2_TVALID : IN STD_LOGIC;
    din_data_q2_TREADY : OUT STD_LOGIC;
    din_data_i3_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_i3_TVALID : IN STD_LOGIC;
    din_data_i3_TREADY : OUT STD_LOGIC;
    din_data_q3_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_q3_TVALID : IN STD_LOGIC;
    din_data_q3_TREADY : OUT STD_LOGIC;
    stream_read_to_compute_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    stream_read_to_compute_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_read_to_compute_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_read_to_compute_full_n : IN STD_LOGIC;
    stream_read_to_compute_write : OUT STD_LOGIC );
end;


architecture behav of pfb_multichannel_decimator_read_inputs is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal din_data_i0_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln12_fu_125_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal din_data_q0_TDATA_blk_n : STD_LOGIC;
    signal din_data_i1_TDATA_blk_n : STD_LOGIC;
    signal din_data_q1_TDATA_blk_n : STD_LOGIC;
    signal din_data_i2_TDATA_blk_n : STD_LOGIC;
    signal din_data_q2_TDATA_blk_n : STD_LOGIC;
    signal din_data_i3_TDATA_blk_n : STD_LOGIC;
    signal din_data_q3_TDATA_blk_n : STD_LOGIC;
    signal stream_read_to_compute_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal pack_i_reg_165 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal pack_q_reg_170 : STD_LOGIC_VECTOR (15 downto 0);
    signal pack_i_1_reg_175 : STD_LOGIC_VECTOR (15 downto 0);
    signal pack_q_1_reg_180 : STD_LOGIC_VECTOR (15 downto 0);
    signal pack_i_2_reg_185 : STD_LOGIC_VECTOR (15 downto 0);
    signal pack_q_2_reg_190 : STD_LOGIC_VECTOR (15 downto 0);
    signal pack_i_3_reg_195 : STD_LOGIC_VECTOR (15 downto 0);
    signal pack_q_3_reg_200 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal i_fu_58 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal i_4_fu_131_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_din_data_i0_U_apdone_blk : STD_LOGIC;
    signal din_data_i0_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal din_data_i0_TVALID_int_regslice : STD_LOGIC;
    signal din_data_i0_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_din_data_i0_U_ack_in : STD_LOGIC;
    signal regslice_both_din_data_q0_U_apdone_blk : STD_LOGIC;
    signal din_data_q0_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal din_data_q0_TVALID_int_regslice : STD_LOGIC;
    signal din_data_q0_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_din_data_q0_U_ack_in : STD_LOGIC;
    signal regslice_both_din_data_i1_U_apdone_blk : STD_LOGIC;
    signal din_data_i1_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal din_data_i1_TVALID_int_regslice : STD_LOGIC;
    signal din_data_i1_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_din_data_i1_U_ack_in : STD_LOGIC;
    signal regslice_both_din_data_q1_U_apdone_blk : STD_LOGIC;
    signal din_data_q1_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal din_data_q1_TVALID_int_regslice : STD_LOGIC;
    signal din_data_q1_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_din_data_q1_U_ack_in : STD_LOGIC;
    signal regslice_both_din_data_i2_U_apdone_blk : STD_LOGIC;
    signal din_data_i2_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal din_data_i2_TVALID_int_regslice : STD_LOGIC;
    signal din_data_i2_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_din_data_i2_U_ack_in : STD_LOGIC;
    signal regslice_both_din_data_q2_U_apdone_blk : STD_LOGIC;
    signal din_data_q2_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal din_data_q2_TVALID_int_regslice : STD_LOGIC;
    signal din_data_q2_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_din_data_q2_U_ack_in : STD_LOGIC;
    signal regslice_both_din_data_i3_U_apdone_blk : STD_LOGIC;
    signal din_data_i3_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal din_data_i3_TVALID_int_regslice : STD_LOGIC;
    signal din_data_i3_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_din_data_i3_U_ack_in : STD_LOGIC;
    signal regslice_both_din_data_q3_U_apdone_blk : STD_LOGIC;
    signal din_data_q3_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal din_data_q3_TVALID_int_regslice : STD_LOGIC;
    signal din_data_q3_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_din_data_q3_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pfb_multichannel_decimator_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_din_data_i0_U : component pfb_multichannel_decimator_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => din_data_i0_TDATA,
        vld_in => din_data_i0_TVALID,
        ack_in => regslice_both_din_data_i0_U_ack_in,
        data_out => din_data_i0_TDATA_int_regslice,
        vld_out => din_data_i0_TVALID_int_regslice,
        ack_out => din_data_i0_TREADY_int_regslice,
        apdone_blk => regslice_both_din_data_i0_U_apdone_blk);

    regslice_both_din_data_q0_U : component pfb_multichannel_decimator_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => din_data_q0_TDATA,
        vld_in => din_data_q0_TVALID,
        ack_in => regslice_both_din_data_q0_U_ack_in,
        data_out => din_data_q0_TDATA_int_regslice,
        vld_out => din_data_q0_TVALID_int_regslice,
        ack_out => din_data_q0_TREADY_int_regslice,
        apdone_blk => regslice_both_din_data_q0_U_apdone_blk);

    regslice_both_din_data_i1_U : component pfb_multichannel_decimator_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => din_data_i1_TDATA,
        vld_in => din_data_i1_TVALID,
        ack_in => regslice_both_din_data_i1_U_ack_in,
        data_out => din_data_i1_TDATA_int_regslice,
        vld_out => din_data_i1_TVALID_int_regslice,
        ack_out => din_data_i1_TREADY_int_regslice,
        apdone_blk => regslice_both_din_data_i1_U_apdone_blk);

    regslice_both_din_data_q1_U : component pfb_multichannel_decimator_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => din_data_q1_TDATA,
        vld_in => din_data_q1_TVALID,
        ack_in => regslice_both_din_data_q1_U_ack_in,
        data_out => din_data_q1_TDATA_int_regslice,
        vld_out => din_data_q1_TVALID_int_regslice,
        ack_out => din_data_q1_TREADY_int_regslice,
        apdone_blk => regslice_both_din_data_q1_U_apdone_blk);

    regslice_both_din_data_i2_U : component pfb_multichannel_decimator_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => din_data_i2_TDATA,
        vld_in => din_data_i2_TVALID,
        ack_in => regslice_both_din_data_i2_U_ack_in,
        data_out => din_data_i2_TDATA_int_regslice,
        vld_out => din_data_i2_TVALID_int_regslice,
        ack_out => din_data_i2_TREADY_int_regslice,
        apdone_blk => regslice_both_din_data_i2_U_apdone_blk);

    regslice_both_din_data_q2_U : component pfb_multichannel_decimator_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => din_data_q2_TDATA,
        vld_in => din_data_q2_TVALID,
        ack_in => regslice_both_din_data_q2_U_ack_in,
        data_out => din_data_q2_TDATA_int_regslice,
        vld_out => din_data_q2_TVALID_int_regslice,
        ack_out => din_data_q2_TREADY_int_regslice,
        apdone_blk => regslice_both_din_data_q2_U_apdone_blk);

    regslice_both_din_data_i3_U : component pfb_multichannel_decimator_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => din_data_i3_TDATA,
        vld_in => din_data_i3_TVALID,
        ack_in => regslice_both_din_data_i3_U_ack_in,
        data_out => din_data_i3_TDATA_int_regslice,
        vld_out => din_data_i3_TVALID_int_regslice,
        ack_out => din_data_i3_TREADY_int_regslice,
        apdone_blk => regslice_both_din_data_i3_U_apdone_blk);

    regslice_both_din_data_q3_U : component pfb_multichannel_decimator_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => din_data_q3_TDATA,
        vld_in => din_data_q3_TVALID,
        ack_in => regslice_both_din_data_q3_U_ack_in,
        data_out => din_data_q3_TDATA_int_regslice,
        vld_out => din_data_q3_TVALID_int_regslice,
        ack_out => din_data_q3_TREADY_int_regslice,
        apdone_blk => regslice_both_din_data_q3_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_fu_58 <= ap_const_lv11_0;
            elsif (((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i_fu_58 <= i_4_fu_131_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                pack_i_1_reg_175 <= din_data_i1_TDATA_int_regslice;
                pack_i_2_reg_185 <= din_data_i2_TDATA_int_regslice;
                pack_i_3_reg_195 <= din_data_i3_TDATA_int_regslice;
                pack_i_reg_165 <= din_data_i0_TDATA_int_regslice;
                pack_q_1_reg_180 <= din_data_q1_TDATA_int_regslice;
                pack_q_2_reg_190 <= din_data_q2_TDATA_int_regslice;
                pack_q_3_reg_200 <= din_data_q3_TDATA_int_regslice;
                pack_q_reg_170 <= din_data_q0_TDATA_int_regslice;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln12_fu_125_p2, ap_enable_reg_pp0_iter1, ap_block_state1, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((icmp_ln12_fu_125_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) and not(((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln12_fu_125_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter0)));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_pp0_stage0_iter0_assign_proc : process(icmp_ln12_fu_125_p2, din_data_i0_TVALID_int_regslice, din_data_q0_TVALID_int_regslice, din_data_i1_TVALID_int_regslice, din_data_q1_TVALID_int_regslice, din_data_i2_TVALID_int_regslice, din_data_q2_TVALID_int_regslice, din_data_i3_TVALID_int_regslice, din_data_q3_TVALID_int_regslice)
    begin
                ap_block_state2_pp0_stage0_iter0 <= (((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (din_data_q3_TVALID_int_regslice = ap_const_logic_0)) or ((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (din_data_i3_TVALID_int_regslice = ap_const_logic_0)) or ((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (din_data_q2_TVALID_int_regslice = ap_const_logic_0)) or ((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (din_data_i2_TVALID_int_regslice = ap_const_logic_0)) or ((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (din_data_q1_TVALID_int_regslice = ap_const_logic_0)) or ((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (din_data_i1_TVALID_int_regslice = ap_const_logic_0)) or ((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (din_data_q0_TVALID_int_regslice = ap_const_logic_0)) or ((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (din_data_i0_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state3_pp0_stage0_iter1_assign_proc : process(stream_read_to_compute_full_n)
    begin
                ap_block_state3_pp0_stage0_iter1 <= (stream_read_to_compute_full_n = ap_const_logic_0);
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln12_fu_125_p2)
    begin
        if ((icmp_ln12_fu_125_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    din_data_i0_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, icmp_ln12_fu_125_p2, din_data_i0_TVALID_int_regslice)
    begin
        if (((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_i0_TDATA_blk_n <= din_data_i0_TVALID_int_regslice;
        else 
            din_data_i0_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    din_data_i0_TREADY <= regslice_both_din_data_i0_U_ack_in;

    din_data_i0_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln12_fu_125_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_i0_TREADY_int_regslice <= ap_const_logic_1;
        else 
            din_data_i0_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    din_data_i1_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, icmp_ln12_fu_125_p2, din_data_i1_TVALID_int_regslice)
    begin
        if (((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_i1_TDATA_blk_n <= din_data_i1_TVALID_int_regslice;
        else 
            din_data_i1_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    din_data_i1_TREADY <= regslice_both_din_data_i1_U_ack_in;

    din_data_i1_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln12_fu_125_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_i1_TREADY_int_regslice <= ap_const_logic_1;
        else 
            din_data_i1_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    din_data_i2_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, icmp_ln12_fu_125_p2, din_data_i2_TVALID_int_regslice)
    begin
        if (((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_i2_TDATA_blk_n <= din_data_i2_TVALID_int_regslice;
        else 
            din_data_i2_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    din_data_i2_TREADY <= regslice_both_din_data_i2_U_ack_in;

    din_data_i2_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln12_fu_125_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_i2_TREADY_int_regslice <= ap_const_logic_1;
        else 
            din_data_i2_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    din_data_i3_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, icmp_ln12_fu_125_p2, din_data_i3_TVALID_int_regslice)
    begin
        if (((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_i3_TDATA_blk_n <= din_data_i3_TVALID_int_regslice;
        else 
            din_data_i3_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    din_data_i3_TREADY <= regslice_both_din_data_i3_U_ack_in;

    din_data_i3_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln12_fu_125_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_i3_TREADY_int_regslice <= ap_const_logic_1;
        else 
            din_data_i3_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    din_data_q0_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, icmp_ln12_fu_125_p2, din_data_q0_TVALID_int_regslice)
    begin
        if (((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_q0_TDATA_blk_n <= din_data_q0_TVALID_int_regslice;
        else 
            din_data_q0_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    din_data_q0_TREADY <= regslice_both_din_data_q0_U_ack_in;

    din_data_q0_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln12_fu_125_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_q0_TREADY_int_regslice <= ap_const_logic_1;
        else 
            din_data_q0_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    din_data_q1_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, icmp_ln12_fu_125_p2, din_data_q1_TVALID_int_regslice)
    begin
        if (((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_q1_TDATA_blk_n <= din_data_q1_TVALID_int_regslice;
        else 
            din_data_q1_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    din_data_q1_TREADY <= regslice_both_din_data_q1_U_ack_in;

    din_data_q1_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln12_fu_125_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_q1_TREADY_int_regslice <= ap_const_logic_1;
        else 
            din_data_q1_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    din_data_q2_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, icmp_ln12_fu_125_p2, din_data_q2_TVALID_int_regslice)
    begin
        if (((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_q2_TDATA_blk_n <= din_data_q2_TVALID_int_regslice;
        else 
            din_data_q2_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    din_data_q2_TREADY <= regslice_both_din_data_q2_U_ack_in;

    din_data_q2_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln12_fu_125_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_q2_TREADY_int_regslice <= ap_const_logic_1;
        else 
            din_data_q2_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    din_data_q3_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, icmp_ln12_fu_125_p2, din_data_q3_TVALID_int_regslice)
    begin
        if (((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_q3_TDATA_blk_n <= din_data_q3_TVALID_int_regslice;
        else 
            din_data_q3_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    din_data_q3_TREADY <= regslice_both_din_data_q3_U_ack_in;

    din_data_q3_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln12_fu_125_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln12_fu_125_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_q3_TREADY_int_regslice <= ap_const_logic_1;
        else 
            din_data_q3_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    i_4_fu_131_p2 <= std_logic_vector(unsigned(i_fu_58) + unsigned(ap_const_lv11_1));
    icmp_ln12_fu_125_p2 <= "1" when (i_fu_58 = ap_const_lv11_400) else "0";

    stream_read_to_compute_blk_n_assign_proc : process(stream_read_to_compute_full_n, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_read_to_compute_blk_n <= stream_read_to_compute_full_n;
        else 
            stream_read_to_compute_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_read_to_compute_din <= (((((((pack_q_3_reg_200 & pack_i_3_reg_195) & pack_q_2_reg_190) & pack_i_2_reg_185) & pack_q_1_reg_180) & pack_i_1_reg_175) & pack_q_reg_170) & pack_i_reg_165);

    stream_read_to_compute_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_read_to_compute_write <= ap_const_logic_1;
        else 
            stream_read_to_compute_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
